# Configuration to connect to broker gateway for service registration
broker.remote.gateway.url=http://localhost:8081

# Host server heartbeat registration
host.server.url=http://localhost:8085
host.server.registration.enabled=true
service.name=file-service
service.host=localhost
service.framework=Spring Boot
service.version=1.0.0
service.operations=getFile,listFiles,deleteFile,createFile
heartbeat.interval.ms=30000

#spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus?currentSchema=file_service
spring.datasource.username=pguser
spring.datasource.password=pgpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect