/**
 * Catalog -> ordered SQL migration.
 *
 * Structure (order matters):
 *   1. field get-or-create INSERTs ... ON CONFLICT (property_name) DO NOTHING
 *      (explicit here so the migration is reviewable and deterministic even
 *      though stereotype_create_revision would also get-or-create);
 *   2. one SELECT shrapnel.stereotype_create_revision(...) per revision, in
 *      topological order, with the parent expressed as a subselect on
 *      stereotype_resolve() so the DB resolves the head revision at apply
 *      time (cross-stereotype parenting lands correctly via the function's
 *      composite-key handling);
 *   3. a verification SELECT echoing the applied catalog as the migration's
 *      own evidence.
 *
 * The migration is wrapped in BEGIN/COMMIT: the deferred fingerprint v2,
 * superset v2, and field-integrity triggers verify the WHOLE migration
 * atomically at COMMIT — a single invariant violation aborts everything.
 */
import type { Catalog } from "./catalog.js";

export function renderSql(catalog: Catalog): string {
  const lines: string[] = [];

  lines.push(`-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)`);
  lines.push(`-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)`);
  lines.push(`-- Fingerprints, superset conformance, depth, and freeze are enforced by`);
  lines.push(`-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).`);
  lines.push(`BEGIN;`);
  lines.push(``);

  // ── 1. Fields ──────────────────────────────────────────────────────────
  lines.push(`-- ── fields (get-or-create; type codes from the 0001 registry) ──`);
  for (const f of catalog.fields.values()) {
    lines.push(
      `INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) ` +
        `VALUES (${f.is_calculated}, ${f.field_index}, ${sqlString(f.label)}, ${sqlString(f.name)}, ` +
        `${sqlString(f.property_name)}, ${f.field_type_code}) ` +
        `ON CONFLICT (property_name) DO NOTHING;`
    );
  }
  lines.push(``);

  // ── 2. Revisions in topological order ─────────────────────────────────
  lines.push(`-- ── stereotype revisions (topological; parent = parent's head) ──`);
  for (const r of catalog.revisions) {
    const required = r.fields.filter((f) => f.required).map((f) => f.property_name);
    const optional = r.fields.filter((f) => !f.required).map((f) => f.property_name);

    const parentExpr = r.parentStereotypeName
      ? `(SELECT head_revision_id FROM shrapnel.stereotype_resolve(${sqlString(r.parentStereotypeName)}))`
      : `NULL`;
    const rationaleExpr = r.rationale !== undefined ? sqlString(r.rationale) : `NULL`;

    lines.push(
      `SELECT shrapnel.stereotype_create_revision(` +
        `${sqlString(r.stereotypeName)}, ${parentExpr}, ${rationaleExpr}, ` +
        `${sqlTextArray(required)}, ${sqlTextArray(optional)});`
    );
  }
  lines.push(``);

  // ── 3. Verification echo (the migration's own evidence) ───────────────
  lines.push(`-- ── verification echo: what the catalog now holds ──`);
  lines.push(`SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,`);
  lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,`);
  lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields`);
  lines.push(`FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id`);
  lines.push(`ORDER BY s.name, r.version;`);
  lines.push(``);
  lines.push(`COMMIT;`);
  lines.push(``);

  return lines.join("\n");
}

function sqlString(s: string | undefined): string {
  if (s === undefined) return `NULL`;
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlTextArray(items: string[]): string {
  if (items.length === 0) return `ARRAY[]::text[]`;
  return `ARRAY[${items.map(sqlString).join(", ")}]::text[]`;
}
