/**
 * Catalog -> ordered SQL migration.
 *
 * Structure (order matters):
 *   1. field get-or-create INSERTs ... ON CONFLICT (property_name) DO NOTHING
 *      (explicit here so the migration is reviewable and deterministic even
 *      though stereotype_create_revision would also get-or-create);
 *   2. one SELECT shrapnel.stereotype_create_revision(...) per revision, in
 *      topological order, with the parent expressed as a subselect on
 *      stereotype_resolve() so the DB resolves the head revision at apply
 *      time (cross-stereotype parenting lands correctly via the function's
 *      composite-key handling);
 *   3. a verification SELECT echoing the applied catalog as the migration's
 *      own evidence.
 *
 * The migration is wrapped in BEGIN/COMMIT: the deferred fingerprint v2,
 * superset v2, and field-integrity triggers verify the WHOLE migration
 * atomically at COMMIT — a single invariant violation aborts everything.
 */
import type { Catalog } from "./catalog.js";

export interface RenderOptions {
  /**
   * Emit `stereotype_reconcile` instead of `stereotype_create_revision`.
   *
   * reconcile writes nothing when the declared state already matches the head
   * revision, so re-applying an unchanged catalog is a no-op instead of minting
   * a new revision every time (migration 0008; #591's first "known limit").
   *
   * DEFAULT IS FALSE, deliberately, and this is a change of position from the
   * design discussion where I argued reconcile should become the default verb.
   * That argument was made before noticing that compile.e2e asserts the emitted
   * SQL is byte-identical to the #591 committed evidence, which uses
   * create_revision. Flipping the default would invalidate a reproducibility
   * artifact that is the whole reason those files are committed. So reconcile
   * is opt-in per project, and the default keeps its exact current output.
   */
  reconcile?: boolean;
}

export function renderSql(catalog: Catalog, options: RenderOptions = {}): string {
  const reconcile = options.reconcile === true;
  // The verb differs ONLY in which function is called. The argument list is
  // deliberately identical between the two, so the two emitted forms differ
  // only in the function name.
  const revisionFn = reconcile
    ? "shrapnel.stereotype_reconcile"
    : "shrapnel.stereotype_create_revision";
  const lines: string[] = [];

  lines.push(`-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)`);
  lines.push(
    reconcile
      ? `-- Target API: shrapnel.stereotype_reconcile (0008_stereotype_reconcile.sql)`
      : `-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)`
  );
  lines.push(`-- Fingerprints, superset conformance, depth, and freeze are enforced by`);
  lines.push(`-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).`);
  if (reconcile) {
    lines.push(`-- RECONCILE MODE: re-applying this file unchanged mints no revisions.`);
    lines.push(`-- Idempotence holds when the declared state AND its whole upstream`);
    lines.push(`-- closure are unchanged: a new parent head legitimately mints a child`);
    lines.push(`-- revision even when the child's own fields are unchanged, because`);
    lines.push(`-- p_extends_revision is inside the contract fingerprint.`);
  }
  lines.push(`BEGIN;`);
  lines.push(``);

  // ── 1. Fields ──────────────────────────────────────────────────────────
  lines.push(`-- ── fields (get-or-create; type codes from the 0001 registry) ──`);
  for (const f of catalog.fields.values()) {
    lines.push(
      `INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) ` +
        `VALUES (${f.is_calculated}, ${f.field_index}, ${sqlString(f.label)}, ${sqlString(f.name)}, ` +
        `${sqlString(f.property_name)}, ${f.field_type_code}) ` +
        `ON CONFLICT (property_name) DO NOTHING;`
    );
  }
  lines.push(``);

  // ── 2. Revisions in topological order ─────────────────────────────────
  if (reconcile) {
    // Capture each call's verdict so the echo can report created-vs-reconciled.
    // On the no-op path none of the deferred triggers fire, so without this the
    // echo is the only thing distinguishing "correctly skipped" from
    // "silently wrong" — and without the echo, idempotence is unobservable.
    lines.push(`-- ── per-call verdicts (created vs reconciled) ──`);
    lines.push(`CREATE TEMP TABLE _tsp_reconcile_result (`);
    lines.push(`  stereotype_name text PRIMARY KEY,`);
    lines.push(`  revision_id     bigint NOT NULL,`);
    lines.push(`  created         boolean NOT NULL`);
    lines.push(`) ON COMMIT DROP;`);
    lines.push(``);
  }
  lines.push(`-- ── stereotype revisions (topological; parent = parent's head) ──`);
  for (const r of catalog.revisions) {
    const required = r.fields.filter((f) => f.required).map((f) => f.property_name);
    const optional = r.fields.filter((f) => !f.required).map((f) => f.property_name);

    const parentExpr = r.parentStereotypeName
      ? `(SELECT head_revision_id FROM shrapnel.stereotype_resolve(${sqlString(r.parentStereotypeName)}))`
      : `NULL`;
    const rationaleExpr = r.rationale !== undefined ? sqlString(r.rationale) : `NULL`;

    const call =
      `${revisionFn}(` +
      `${sqlString(r.stereotypeName)}, ${parentExpr}, ${rationaleExpr}, ` +
      `${sqlTextArray(required)}, ${sqlTextArray(optional)})`;

    if (reconcile) {
      lines.push(
        `INSERT INTO _tsp_reconcile_result (stereotype_name, revision_id, created) ` +
          `SELECT ${sqlString(r.stereotypeName)}, * FROM ${call};`
      );
    } else {
      lines.push(`SELECT ${call};`);
    }
  }
  lines.push(``);

  // ── 1b. Instance-storage registrations (@instanceStorage) ─────────────
  // Deliberately OUTSIDE the type contract: no stereotype_field rows, no
  // fingerprint involvement. The registration table must exist before this
  // migration runs (see README: migration 0007 proposal, pending DBA).
  if (catalog.storageRegistrations.length > 0) {
    lines.push(`-- ── instance-storage registrations (metadata, NOT contract) ──`);
    for (const r of catalog.storageRegistrations) {
      lines.push(
        `INSERT INTO shrapnel.stereotype_instance_storage (stereotype_name, storage_class, revision_ref) ` +
          `VALUES (${sqlString(r.stereotypeName)}, ${sqlString(r.storage)}, ` +
          `(SELECT id FROM shrapnel.stereotype_revision WHERE stereotype_id = ` +
          `(SELECT id FROM shrapnel.stereotype WHERE name = ${sqlString(r.stereotypeName)}) ` +
          `ORDER BY version DESC LIMIT 1)) ` +
          `ON CONFLICT (stereotype_name) DO UPDATE SET storage_class = EXCLUDED.storage_class, revision_ref = EXCLUDED.revision_ref;`
      );
    }
    lines.push(``);
  }

  // ── 3. Verification echo (the migration's own evidence) ───────────────
  if (reconcile) {
    // In reconcile mode the useful question changes from "what was created?"
    // to "what changed?". One row per call, so a re-apply reads as
    // "reconciled" across the board — which is what makes the double-apply
    // CI gate's assertion legible in the build log.
    lines.push(`-- ── verification echo: what changed, and what was already current ──`);
    lines.push(`-- action = 'reconciled' means NOTHING was written for that stereotype.`);
    lines.push(`SELECT t.stereotype_name,`);
    lines.push(`       CASE WHEN t.created THEN 'created' ELSE 'reconciled' END AS action,`);
    lines.push(`       r.version, r.depth, r.contract_fingerprint,`);
    lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,`);
    lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields`);
    lines.push(`FROM _tsp_reconcile_result t`);
    lines.push(`JOIN shrapnel.stereotype_revision r ON r.id = t.revision_id`);
    lines.push(`ORDER BY t.stereotype_name;`);
  } else {
    lines.push(`-- ── verification echo: what the catalog now holds ──`);
    lines.push(`SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,`);
    lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,`);
    lines.push(`       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields`);
    lines.push(`FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id`);
    lines.push(`ORDER BY s.name, r.version;`);
  }
  lines.push(``);
  lines.push(`COMMIT;`);
  lines.push(``);

  return lines.join("\n");
}

function sqlString(s: string | undefined): string {
  if (s === undefined) return `NULL`;
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlTextArray(items: string[]): string {
  if (items.length === 0) return `ARRAY[]::text[]`;
  return `ARRAY[${items.map(sqlString).join(", ")}]::text[]`;
}
