# Google Search API
google.search.api.key=AIzaSyAfVHkNv8-YVyz1eSitseZLTHcXW4NTyI4
google.search.engine.id=e44fd2743cc9e49c8

# YouTube Search API
youtube.api.key=AIzaSyAfVHkNv8-YVyz1eSitseZLTHcXW4NTyI4
