-- Seed: Conduit → WRP Bridge Projection
-- Registers the conduit-wrp-bridge projection definition in nebula.projections.
--
-- This projection renders a WRP (WorkRequest Protocol) state projection
-- for each conduit plan, derived deterministically from its receipt stream.
--
-- Spec: audit/SPECS/CONDUIT_WRP_BRIDGE.md
-- TS contract: typescript/nebula-mcp/src/conduit-wrp-contract.ts
-- Python reducer: python/absorb/html/conduit_wrp_reducer.py
-- Plan reference: #0174
--
-- Idempotent: ON CONFLICT (name) DO NOTHING

INSERT INTO nebula.projections (name, type, description, source_query, template, target_path, metadata)
VALUES
(
    'conduit-wrp-bridge',
    'deterministic',
    'Renders WRP protocol state projections from Conduit receipt streams — '
    'deterministic state machine fold with stratification and cross-references',
    $q$
WITH plan_receipts AS (
    SELECT
        p.id::text AS plan_id,
        p.title::text AS title,
        p.project::text AS project,
        p.goal::text AS goal,
        p.files_affected::text AS files_affected_json,
        p.acceptance_criteria::text AS acceptance_criteria_json,
        p.dependencies::text AS dependencies_json,
        COALESCE(p.prompt_ref, '')::text AS prompt_ref,
        jsonb_agg(
            jsonb_build_object(
                'id',            r.id,
                'type',          r.type,
                'agent_role',    r.agent_role,
                'created_at',    r.created_at,
                'summary',       r.summary,
                'metadata',      r.metadata_json::jsonb,
                'session_id',    r.session_id,
                'ticket_id',     r.ticket_id,
                'artifact_path', r.artifact_path,
                'tokens_used',   r.tokens_used
            )
            ORDER BY r.created_at ASC, r.id ASC
        ) FILTER (WHERE r.id IS NOT NULL) AS receipts_json,
        COUNT(r.id)::integer AS total_receipts,
        SUM(CASE WHEN r.type IN ('BLOCK','PLAN_BLOCK','API_LIMIT') THEN 1 ELSE 0 END)::integer
            AS exception_count
    FROM nebula.plans p
    LEFT JOIN vision.receipts r ON r.plan_id = p.id
    WHERE p.deleted = 0
    GROUP BY p.id, p.title, p.project, p.goal, p.files_affected,
             p.acceptance_criteria, p.dependencies, p.prompt_ref
)
SELECT
    plan_id,
    title,
    project,
    goal,
    CASE
        WHEN files_affected_json = '' OR files_affected_json IS NULL
        THEN '[]'::jsonb
        ELSE files_affected_json::jsonb
    END AS files_affected,
    CASE
        WHEN acceptance_criteria_json = '' OR acceptance_criteria_json IS NULL
        THEN '[]'::jsonb
        ELSE acceptance_criteria_json::jsonb
    END AS acceptance_criteria,
    CASE
        WHEN dependencies_json = '' OR dependencies_json IS NULL
        THEN '[]'::jsonb
        ELSE dependencies_json::jsonb
    END AS dependencies,
    prompt_ref,
    COALESCE(receipts_json, '[]'::jsonb) AS receipts,
    total_receipts,
    exception_count
FROM plan_receipts
ORDER BY plan_id ASC;
    $q$,
    $q$# WRP Projection: {{title}}

**Plan:** {{plan_id}}
**Project:** {{project}}
**State:** {{wrp_state}}
**Level:** {{abstraction_level}}
**Scope:** {{visibility_scope}}

---

## Goal

{{goal}}

---

## Stratified Chunks

{{#chunks}}
- **{{chunk_kind}}** ({{level}}, {{visibility_scope}}): {{content}}
{{/chunks}}

---

## Receipts ({{total_receipts}})

{{#receipts}}
- {{created_at}} | **{{type}}** | {{agent_role}} | {{summary}}
{{/receipts}}

---

## Cross-References

{{#cross_references}}
- {{source_id}} **{{rel_type}}** {{target_id}}
{{/cross_references}}

---

*Projection generated by conduit-wrp-bridge v0.1*
    $q$,
    'wrp/projections/{{plan_id}}.md',
    '{
        "spec": "audit/SPECS/CONDUIT_WRP_BRIDGE.md",
        "version": "0.1",
        "plan_ref": "0174",
        "ordering_key": ["created_at ASC", "receipt_id ASC"],
        "generator": "conduit-wrp-bridge"
    }'::jsonb
)
ON CONFLICT (name) DO NOTHING;
