/*
|--------------------------------------------------------------------------
| Control-plane edge — route table
|--------------------------------------------------------------------------
|
| One AdonisJS process hosting the control-plane REST surfaces:
| ui-tools, tools-aggregator, knowledge-srv, semantics-srv, terrain-srv,
| voyager-srv, tackle-srv, tackle-prompt-sync-srv, role-memory-srv
| (per binding ruling D-2026-08-14-002).
|
| Each domain registers its routes in a named group so the boot-time
| conformance validator can diff the route table against the emitted
| TypeSpec/OpenAPI contract (D-2026-08-14-004 Phase A).
|
*/

import router from '@adonisjs/core/services/router'

// ── Health ────────────────────────────────────────────────────────────
router.get('/health', [() => import('#controllers/health_controller'), 'index'])

// ── conduit-srv (re-homed Wave 3.3) ───────────────────────────────────
// Ported from nexus/typescript/conduit-srv/src/routes/*.ts. Mounted at
// ROOT level (no /api prefix) for backward compat with conduit-mcp
// consumers, matching the original service. Queries run against the
// `conduit` named connection (search_path=conduit,vision,peb,tackle).
router.group(() => {
  router.get('/workflows', [() => import('#controllers/conduit_controller'), 'listWorkflows'])
  router.post('/tickets/detect', [() => import('#controllers/conduit_controller'), 'detectTickets'])
  router.get('/tickets/lineage/:planId', [() => import('#controllers/conduit_controller'), 'ticketLineage'])
  router.get('/tokens/plan/:planId', [() => import('#controllers/conduit_controller'), 'tokensByPlan'])
  router.get('/tokens/role/:role', [() => import('#controllers/conduit_controller'), 'tokensByRole'])
  router.get('/tokens/ticket/:ticketId', [() => import('#controllers/conduit_controller'), 'tokensByTicket'])
  router.get('/config/cron', [() => import('#controllers/conduit_controller'), 'getCron'])
  router.get('/config/failure-recovery', [() => import('#controllers/conduit_controller'), 'getFailureRecovery'])
  router.post('/config/failure-recovery', [() => import('#controllers/conduit_controller'), 'saveFailureRecovery'])
  router.get('/log/:sessionId', [() => import('#controllers/conduit_controller'), 'sessionLog'])
  router.post('/governance/replay', [() => import('#controllers/conduit_controller'), 'replayGovernance'])
  router.get('/governance/events', [() => import('#controllers/conduit_controller'), 'listGovernanceEvents'])
  router.post('/vision/work-requests', [() => import('#controllers/conduit_controller'), 'upsertWorkRequest'])
  router.get('/vision/work-requests', [() => import('#controllers/conduit_controller'), 'listWorkRequests'])
  router.get('/vision/work-requests/:id', [() => import('#controllers/conduit_controller'), 'getWorkRequest'])
  router.get('/vision/receipts', [() => import('#controllers/conduit_controller'), 'listReceipts'])
  router.get('/wr/:id/projection-drift', [() => import('#controllers/conduit_controller'), 'projectionDrift'])
  router.get('/wr/drift-scan', [() => import('#controllers/conduit_controller'), 'driftScan'])
})

// ── wind-srv (re-homed Wave 3.4) ────────────────────────────────────
// Ported from nexus/typescript/wind-srv/src/routes/*.js. All queries
// explicitly `wind.*`-qualified on the default pg connection.
router.group(() => {
  router.get('/api/offices', [() => import('#controllers/wind_org_controller'), 'listOffices'])
  router.get('/api/offices/:id', [() => import('#controllers/wind_org_controller'), 'getOffice'])
  router.post('/api/offices', [() => import('#controllers/wind_org_controller'), 'createOffice'])
  router.put('/api/offices/:id', [() => import('#controllers/wind_org_controller'), 'updateOffice'])
  router.delete('/api/offices/:id', [() => import('#controllers/wind_org_controller'), 'deleteOffice'])
  router.get('/api/titles', [() => import('#controllers/wind_org_controller'), 'listTitles'])
  router.get('/api/titles/:id', [() => import('#controllers/wind_org_controller'), 'getTitle'])
  router.post('/api/titles', [() => import('#controllers/wind_org_controller'), 'createTitle'])
  router.put('/api/titles/:id', [() => import('#controllers/wind_org_controller'), 'updateTitle'])
  router.delete('/api/titles/:id', [() => import('#controllers/wind_org_controller'), 'deleteTitle'])
  router.get('/api/v-roles', [() => import('#controllers/wind_org_controller'), 'listVRoles'])
  router.get('/api/v-roles/:name', [() => import('#controllers/wind_org_controller'), 'getVRole'])
  router.get('/api/workflows', [() => import('#controllers/wind_workflow_controller'), 'listWorkflows'])
  router.get('/api/workflows/:id', [() => import('#controllers/wind_workflow_controller'), 'getWorkflow'])
  router.post('/api/workflows', [() => import('#controllers/wind_workflow_controller'), 'createWorkflow'])
  router.put('/api/workflows/:id', [() => import('#controllers/wind_workflow_controller'), 'updateWorkflow'])
  router.delete('/api/workflows/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteWorkflow'])
  router.get('/api/versions', [() => import('#controllers/wind_workflow_controller'), 'listVersions'])
  router.get('/api/versions/:id', [() => import('#controllers/wind_workflow_controller'), 'getVersion'])
  router.post('/api/versions', [() => import('#controllers/wind_workflow_controller'), 'createVersion'])
  router.post('/api/versions/:id/activate', [() => import('#controllers/wind_workflow_controller'), 'activateVersion'])
  router.delete('/api/versions/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteVersion'])
  router.get('/api/nodes', [() => import('#controllers/wind_workflow_controller'), 'listNodes'])
  router.get('/api/nodes/:id', [() => import('#controllers/wind_workflow_controller'), 'getNode'])
  router.post('/api/nodes', [() => import('#controllers/wind_workflow_controller'), 'createNode'])
  router.put('/api/nodes/:id', [() => import('#controllers/wind_workflow_controller'), 'updateNode'])
  router.delete('/api/nodes/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteNode'])
  router.get('/api/edges', [() => import('#controllers/wind_workflow_controller'), 'listEdges'])
  router.post('/api/edges', [() => import('#controllers/wind_workflow_controller'), 'createEdge'])
  router.delete('/api/edges/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteEdge'])
  router.get('/api/tasks', [() => import('#controllers/wind_workflow_controller'), 'listTasks'])
  router.get('/api/tasks/:id', [() => import('#controllers/wind_workflow_controller'), 'getTask'])
  router.post('/api/tasks', [() => import('#controllers/wind_workflow_controller'), 'createTask'])
  router.put('/api/tasks/:id', [() => import('#controllers/wind_workflow_controller'), 'updateTask'])
  router.delete('/api/tasks/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteTask'])
  router.get('/api/outcomes', [() => import('#controllers/wind_workflow_controller'), 'listOutcomes'])
  router.get('/api/outcomes/:id', [() => import('#controllers/wind_workflow_controller'), 'getOutcome'])
  router.post('/api/outcomes', [() => import('#controllers/wind_workflow_controller'), 'createOutcome'])
  router.delete('/api/outcomes/:id', [() => import('#controllers/wind_workflow_controller'), 'deleteOutcome'])
  router.get('/api/instances', [() => import('#controllers/wind_execution_controller'), 'listInstances'])
  router.get('/api/instances/:id', [() => import('#controllers/wind_execution_controller'), 'getInstance'])
  router.post('/api/instances', [() => import('#controllers/wind_execution_controller'), 'startInstance'])
  router.post('/api/instances/:id/pause', [() => import('#controllers/wind_execution_controller'), 'pauseInstance'])
  router.post('/api/instances/:id/resume', [() => import('#controllers/wind_execution_controller'), 'resumeInstance'])
  router.post('/api/instances/:id/stop', [() => import('#controllers/wind_execution_controller'), 'stopInstance'])
  router.post('/api/instances/:id/execute', [() => import('#controllers/wind_execution_controller'), 'executeInstance'])
  router.post('/api/instances/:id/advance', [() => import('#controllers/wind_execution_controller'), 'advanceInstance'])
  router.post('/api/instances/:id/run', [() => import('#controllers/wind_execution_controller'), 'runInstance'])
  router.get('/api/tickets', [() => import('#controllers/wind_execution_controller'), 'listTickets'])
  router.get('/api/tickets/:id', [() => import('#controllers/wind_execution_controller'), 'getTicket'])
  router.put('/api/tickets/:id/status', [() => import('#controllers/wind_execution_controller'), 'updateTicketStatus'])
  router.post('/api/tickets/:id/cancel', [() => import('#controllers/wind_execution_controller'), 'cancelTicket'])
  router.get('/api/receipts', [() => import('#controllers/wind_execution_controller'), 'listReceipts'])
  router.get('/api/receipts/:id', [() => import('#controllers/wind_execution_controller'), 'getReceipt'])
  router.get('/api/validate/:version_id', [() => import('#controllers/wind_execution_controller'), 'validateVersion'])
  router.post('/api/validate/:version_id/structure', [() => import('#controllers/wind_execution_controller'), 'validateStructure'])
  router.get('/api/events', [() => import('#controllers/wind_event_controller'), 'listEvents'])
  router.post('/api/events/poll', [() => import('#controllers/wind_event_controller'), 'pollEvents'])
  router.get('/api/events/:id', [() => import('#controllers/wind_event_controller'), 'getEvent'])
  router.post('/api/events', [() => import('#controllers/wind_event_controller'), 'createEvent'])
  router.get('/api/event-types', [() => import('#controllers/wind_event_controller'), 'listEventTypes'])
  router.get('/api/event-types/:eventType', [() => import('#controllers/wind_event_controller'), 'getEventType'])
  router.post('/api/event-types', [() => import('#controllers/wind_event_controller'), 'createEventType'])
  router.delete('/api/event-types/:eventType', [() => import('#controllers/wind_event_controller'), 'deleteEventType'])
})

// ── kernel-srv: kernel event system ───────────────────────────────────
router.group(() => {
  router.post('/api/kernel/transitions', [() => import('#controllers/kernel_controller'), 'transitions'])
  router.get('/api/kernel/transitions/:event_id', [() => import('#controllers/kernel_controller'), 'transitionById'])
  router.get('/api/kernel/transitions/:event_id/causality', [() => import('#controllers/kernel_controller'), 'causality'])
  router.post('/api/kernel/receipts', [() => import('#controllers/kernel_controller'), 'receipts'])
  router.get('/api/kernel/receipts/:id/chain', [() => import('#controllers/kernel_controller'), 'receiptChain'])
  router.get('/api/kernel/plans/:plan_number/receipts', [() => import('#controllers/kernel_controller'), 'planReceipts'])
  router.get('/api/kernel/aggregates/:aggregate_type/:aggregate_id/events', [() => import('#controllers/kernel_controller'), 'aggregateEvents'])
  router.get('/api/kernel/policy/active', [() => import('#controllers/kernel_controller'), 'policyActive'])
  router.get('/api/kernel/policy/maturity', [() => import('#controllers/kernel_controller'), 'policyMaturity'])
  router.get('/api/kernel/health/recent-events', [() => import('#controllers/kernel_controller'), 'recentEvents'])
  router.get('/api/kernel/health/receipt-integrity', [() => import('#controllers/kernel_controller'), 'receiptIntegrity'])
  router.get('/api/kernel/events/stream', [() => import('#controllers/kernel_controller'), 'eventsStream'])
})

// ── ui-tools: navigation links ────────────────────────────────────────
router.group(() => {
  router.get('/api/links', [() => import('#controllers/links_controller'), 'index'])
  router.post('/api/links', [() => import('#controllers/links_controller'), 'create'])
  router.patch('/api/links/reorder', [() => import('#controllers/links_controller'), 'reorder'])
  router.patch('/api/links/:id', [() => import('#controllers/links_controller'), 'update'])
  router.delete('/api/links/:id', [() => import('#controllers/links_controller'), 'destroy'])
})

// ── tackle-prompt-sync-srv (re-homed Wave 1.1) ────────────────────────
router.group(() => {
  // Wave 3.5 collision resolution: /prompts/:role is the tackle-srv UI
  // contract ({count, prompts} from PG). The prompt-sync Redis port
  // served a bare array here; the UI expects res.prompts. The tackle
  // controller (PG-backed) now owns the path. /prompt/:role/:slug
  // (singular, Redis card) and /refresh stay on prompt_sync.
  router.get('/prompts/:role', [() => import('#controllers/tackle_tasks_controller'), 'listRolePrompts'])
  router.get('/prompt/:role/:slug', [() => import('#controllers/prompt_sync_controller'), 'getPromptCard'])
})

// ── tackle-srv (re-homed Wave 3.5) ───────────────────────────────────
// Ported from nexus/typescript/tackle-srv/src/routes/*.ts. Runs on the
// `tackle` named connection (search_path=tackle,public).
router.group(() => {
  router.get('/config/ai', [() => import('#controllers/tackle_ai_controller'), 'snapshot'])
  router.get('/config/ai/validate', [() => import('#controllers/tackle_ai_controller'), 'validate'])
  router.post('/config/ai/seed-defaults', [() => import('#controllers/tackle_ai_controller'), 'seedDefaults'])
  router.post('/config/ai/import', [() => import('#controllers/tackle_ai_controller'), 'importConfig'])
  router.get('/config/ai/providers', [() => import('#controllers/tackle_ai_controller'), 'listProviders'])
  router.get('/config/ai/provider/:id', [() => import('#controllers/tackle_ai_controller'), 'getProvider'])
  router.post('/config/ai/provider', [() => import('#controllers/tackle_ai_controller'), 'upsertProvider'])
  router.delete('/config/ai/provider/:id', [() => import('#controllers/tackle_ai_controller'), 'deleteProvider'])
  router.get('/config/ai/harnesses', [() => import('#controllers/tackle_ai_controller'), 'listHarnesses'])
  router.get('/config/ai/harness/:id', [() => import('#controllers/tackle_ai_controller'), 'getHarness'])
  router.post('/config/ai/harness', [() => import('#controllers/tackle_ai_controller'), 'upsertHarness'])
  router.delete('/config/ai/harness/:id', [() => import('#controllers/tackle_ai_controller'), 'deleteHarness'])
  router.get('/config/ai/models', [() => import('#controllers/tackle_ai_controller'), 'listModels'])
  router.get('/config/ai/model/:id', [() => import('#controllers/tackle_ai_controller'), 'getModel'])
  router.post('/config/ai/model', [() => import('#controllers/tackle_ai_controller'), 'upsertModel'])
  router.delete('/config/ai/model/:id', [() => import('#controllers/tackle_ai_controller'), 'deleteModel'])
  router.get('/config/ai/roles', [() => import('#controllers/tackle_ai_controller'), 'listRoleConfigs'])
  router.get('/config/ai/role/:role', [() => import('#controllers/tackle_ai_controller'), 'getRoleConfig'])
  router.post('/config/ai/role', [() => import('#controllers/tackle_ai_controller'), 'upsertRoleConfig'])
  router.delete('/config/ai/role/:role', [() => import('#controllers/tackle_ai_controller'), 'deleteRoleConfig'])
  router.get('/config/ai/bundles', [() => import('#controllers/tackle_ai_controller'), 'listBundles'])
  router.get('/config/ai/bundles/:role', [() => import('#controllers/tackle_ai_controller'), 'listRoleBundles'])
  router.get('/config/ai/bundle/:id', [() => import('#controllers/tackle_ai_controller'), 'getBundle'])
  router.post('/config/ai/bundle', [() => import('#controllers/tackle_ai_controller'), 'upsertBundle'])
  router.delete('/config/ai/bundle/:id', [() => import('#controllers/tackle_ai_controller'), 'deleteBundle'])
  router.post('/config/ai/bundles/:role', [() => import('#controllers/tackle_ai_controller'), 'bulkUpsertRoleBundles'])
  router.get('/config/ai/resolve/:role', [() => import('#controllers/tackle_ai_controller'), 'resolveRoleConfig'])
  router.post('/config/ai/test', [() => import('#controllers/tackle_ai_controller'), 'testInvoke'])
  router.post('/config/ai/verify', [() => import('#controllers/tackle_ai_controller'), 'verifyModel'])
  router.get('/config/ai/verify/:sessionId', [() => import('#controllers/tackle_ai_controller'), 'verifyStatus'])
  router.get('/config/ai/tool-access', [() => import('#controllers/tackle_ai_controller'), 'listToolAccess'])
  router.get('/config/ai/tool-access/:role', [() => import('#controllers/tackle_ai_controller'), 'listRoleToolAccess'])
  router.patch('/config/ai/tool-access/:id', [() => import('#controllers/tackle_ai_controller'), 'updateToolAccess'])
  router.get('/sessions', [() => import('#controllers/tackle_ops_controller'), 'listSessions'])
  router.post('/sessions/:sessionId/kill', [() => import('#controllers/tackle_ops_controller'), 'killSession'])
  router.get('/roles', [() => import('#controllers/tackle_ops_controller'), 'listRoles'])
  router.get('/roles/:id', [() => import('#controllers/tackle_ops_controller'), 'getRole'])
  router.post('/roles', [() => import('#controllers/tackle_ops_controller'), 'upsertRole'])
  router.delete('/roles/:id', [() => import('#controllers/tackle_ops_controller'), 'deleteRole'])
  router.get('/scheduler', [() => import('#controllers/tackle_ops_controller'), 'listScheduler'])
  router.get('/scheduler/due', [() => import('#controllers/tackle_ops_controller'), 'listSchedulerDue'])
  router.get('/scheduler/:id', [() => import('#controllers/tackle_ops_controller'), 'getSchedulerEntry'])
  router.post('/scheduler', [() => import('#controllers/tackle_ops_controller'), 'createSchedulerEntry'])
  router.patch('/scheduler/:id', [() => import('#controllers/tackle_ops_controller'), 'updateSchedulerEntry'])
  router.delete('/scheduler/:id', [() => import('#controllers/tackle_ops_controller'), 'deleteSchedulerEntry'])
  router.get('/logs', [() => import('#controllers/tackle_ops_controller'), 'listLogs'])
  router.post('/logs/emit', [() => import('#controllers/tackle_ops_controller'), 'emitLog'])
  router.delete('/logs', [() => import('#controllers/tackle_ops_controller'), 'clearLogs'])
  router.get('/health/history', [() => import('#controllers/tackle_ops_controller'), 'healthHistory'])
  router.get('/health/metrics', [() => import('#controllers/tackle_ops_controller'), 'healthMetrics'])
  router.post('/health/simulate-load', [() => import('#controllers/tackle_ops_controller'), 'simulateLoad'])
  router.get('/tasks/inspector/dispatch', [() => import('#controllers/tackle_tasks_controller'), 'inspectorDispatch'])
  router.get('/tasks', [() => import('#controllers/tackle_tasks_controller'), 'listTasks'])
  router.get('/tasks/:task_slug', [() => import('#controllers/tackle_tasks_controller'), 'getTask'])
  router.post('/tasks', [() => import('#controllers/tackle_tasks_controller'), 'createTask'])
  router.delete('/tasks/:task_slug', [() => import('#controllers/tackle_tasks_controller'), 'deleteTask'])
  router.get('/prompts', [() => import('#controllers/tackle_tasks_controller'), 'listPrompts'])
  router.post('/prompts', [() => import('#controllers/tackle_tasks_controller'), 'createPrompt'])
  router.get('/prompts/:role/:slug', [() => import('#controllers/tackle_tasks_controller'), 'getRolePrompt'])
  router.get('/memory/procedures/:role', [() => import('#controllers/tackle_memory_controller'), 'roleProcedures'])
  router.get('/memory/procedure/:slug', [() => import('#controllers/tackle_memory_controller'), 'procedureBySlug'])
  router.post('/memory/check-since', [() => import('#controllers/tackle_memory_controller'), 'checkSince'])
  router.post('/memory/refresh', [() => import('#controllers/tackle_memory_controller'), 'refreshMemory'])
  router.get('/memory/role-updates', [() => import('#controllers/tackle_memory_controller'), 'roleUpdates'])
  router.get('/projections', [() => import('#controllers/tackle_projection_controller'), 'listProjections'])
  router.get('/projections/drift', [() => import('#controllers/tackle_projection_controller'), 'drift'])
  router.get('/projections/:id', [() => import('#controllers/tackle_projection_controller'), 'getProjection'])
  router.post('/projections', [() => import('#controllers/tackle_projection_controller'), 'createProjection'])
  router.put('/projections/:id', [() => import('#controllers/tackle_projection_controller'), 'updateProjection'])
  router.post('/projections/:id/render', [() => import('#controllers/tackle_projection_controller'), 'renderProjectionRoute'])
  router.post('/projections/render-all', [() => import('#controllers/tackle_projection_controller'), 'renderAll'])
})

// ── role-memory-srv (re-homed Wave 1.2) ────────────────────────────────
router.group(() => {
  router.get('/procedures/:role', [() => import('#controllers/memory_controller'), 'procedures'])
  router.get('/procedure/:slug', [() => import('#controllers/memory_controller'), 'procedure'])
})

// ── knowledge-srv (re-homed Wave 2.1) ─────────────────────────────────
router.group(() => {
  router.get('/knowledge/entities', [() => import('#controllers/knowledge_controller'), 'entities'])
  router.get('/knowledge/entities/:section/:entity_id', [() => import('#controllers/knowledge_controller'), 'entity'])
  router.get('/knowledge/entities/:section/:entity_id/relations', [() => import('#controllers/knowledge_controller'), 'relations'])
  router.get('/knowledge/edges', [() => import('#controllers/knowledge_controller'), 'edges'])
  router.get('/knowledge/cross-references', [() => import('#controllers/knowledge_controller'), 'crossReferences'])
  router.get('/knowledge/migrations', [() => import('#controllers/knowledge_controller'), 'migrations'])
  router.get('/knowledge/summary', [() => import('#controllers/knowledge_controller'), 'summary'])
})

// ── refresh: repopulate both caches (prompt:* + mem:*) from PG ────────
router.post('/refresh', [() => import('#controllers/prompt_sync_controller'), 'refresh'])

// ── semantics-srv (re-homed Wave 2.2) ─────────────────────────────────
// SOL IR backbone. Generic per-table CRUD is registry-driven; the special
// routes below are registered FIRST so they win over the `:table` wildcard
// (Adonis matches in registration order).
router.group(() => {
  // Meta + filter-list overrides (2-segment, registered before generic).
  router.get('/api/meta', [() => import('#controllers/semantics_controller'), 'meta'])
  router.get('/api/evidence_item', [() => import('#controllers/semantics_controller'), 'evidenceItems'])
  router.get('/api/statement_evidence', [() => import('#controllers/semantics_controller'), 'statementEvidence'])

  // Envelope routes (override generic GET /api/:table/:id).
  router.get('/api/canonical_asset/:id', [() => import('#controllers/semantics_controller'), 'assetEnvelope'])
  router.get('/api/asset_revision/:id', [() => import('#controllers/semantics_controller'), 'revisionEnvelope'])

  // Evidence join endpoints.
  router.get('/api/concept_relationship/:id/evidence', [() => import('#controllers/semantics_controller'), 'conceptRelationshipEvidence'])
  router.get('/api/representation_relationship/:id/evidence', [() => import('#controllers/semantics_controller'), 'representationRelationshipEvidence'])

  // T02 asset sub-resources.
  router.get('/api/canonical_asset/:id/revisions', [() => import('#controllers/semantics_controller'), 'assetRevisions'])
  router.post('/api/canonical_asset/:id/revisions', [() => import('#controllers/semantics_controller'), 'createAssetRevision'])
  router.get('/api/canonical_asset/:id/identity-claims', [() => import('#controllers/semantics_controller'), 'assetClaims'])
  router.post('/api/canonical_asset/:id/identity-claims', [() => import('#controllers/semantics_controller'), 'createAssetClaim'])
  router.get('/api/canonical_asset/:id/relations', [() => import('#controllers/semantics_controller'), 'assetRelations'])
  router.post('/api/canonical_asset/:id/relations', [() => import('#controllers/semantics_controller'), 'createAssetRelation'])
  router.get('/api/canonical_asset/:id/external-ids', [() => import('#controllers/semantics_controller'), 'assetExternalIds'])
  router.post('/api/canonical_asset/:id/external-ids', [() => import('#controllers/semantics_controller'), 'createExternalId'])
  router.delete('/api/canonical_asset/:id/external-ids/:eid', [() => import('#controllers/semantics_controller'), 'deleteExternalId'])

  // Lifecycle transitions.
  router.post('/api/asset_identity_claim/:id/resolve', [() => import('#controllers/semantics_controller'), 'resolveClaim'])
  router.post('/api/drift_finding/:id/resolve', [() => import('#controllers/semantics_controller'), 'resolveDriftFinding'])
})

// ── assembly-srv (re-homed Wave 3.2) — genuine assembly domain ───────
// Ported from nexus/typescript/assembly-srv/src/routes/{forums,feed,users,
// bridges,duality}.js. The 13 camelCase proxy routers (agent-records,
// harvests, plans, requirements, agendas, candidates, conversations,
// intents, assessments, observations, specifications, work-requests,
// open-questions) are NOT re-registered — their paths are already served
// by the nebula-srv surface above (same path, canonical contract).
// Static-literal routes are registered before their :param variants.
router.group(() => {
  // forums
  router.get('/api/forums', [() => import('#controllers/assembly_forum_controller'), 'listForums'])
  router.get('/api/forums/by-slug/:slug', [() => import('#controllers/assembly_forum_controller'), 'getForumBySlug'])
  router.get('/api/forums/by-id/:id', [() => import('#controllers/assembly_forum_controller'), 'getForumById'])
  router.post('/api/forums/by-id/:forumId/threads', [() => import('#controllers/assembly_forum_controller'), 'createThreadByForumId'])
  router.get('/api/forums/by-id/:forumId/threads', [() => import('#controllers/assembly_forum_controller'), 'listThreadsByForumId'])
  router.get('/api/forums/threads/:threadId', [() => import('#controllers/assembly_forum_controller'), 'getThread'])
  router.post('/api/forums/threads/:threadId/comments', [() => import('#controllers/assembly_forum_controller'), 'addComment'])
  router.delete('/api/forums/threads/:threadId', [() => import('#controllers/assembly_forum_controller'), 'deleteThread'])
  router.get('/api/forums/search/by-name', [() => import('#controllers/assembly_forum_controller'), 'searchForumsByName'])
  router.get('/api/forums/search/by-thread-title', [() => import('#controllers/assembly_forum_controller'), 'searchThreadsByTitle'])
  router.get('/api/forums/comments/:id', [() => import('#controllers/assembly_forum_controller'), 'getComment'])
  router.delete('/api/forums/comments/:id', [() => import('#controllers/assembly_forum_controller'), 'deleteComment'])
  router.post('/api/forums/move-thread', [() => import('#controllers/assembly_forum_controller'), 'moveThread'])
  router.put('/api/forums/reorder', [() => import('#controllers/assembly_forum_controller'), 'reorderForums'])
  router.get('/api/forums/:slug/threads', [() => import('#controllers/assembly_forum_controller'), 'listThreadsBySlug'])
  router.post('/api/forums/:slug/threads', [() => import('#controllers/assembly_forum_controller'), 'createThreadBySlug'])
  router.post('/api/forums', [() => import('#controllers/assembly_forum_controller'), 'createForum'])
  router.put('/api/forums/:id', [() => import('#controllers/assembly_forum_controller'), 'updateForum'])
  router.delete('/api/forums/:id', [() => import('#controllers/assembly_forum_controller'), 'deleteForum'])
  // feed
  router.get('/api/feed', [() => import('#controllers/assembly_forum_controller'), 'listFeed'])
  router.post('/api/feed', [() => import('#controllers/assembly_forum_controller'), 'createFeedPost'])
  router.delete('/api/feed/:id', [() => import('#controllers/assembly_forum_controller'), 'deleteFeedPost'])
  // users
  router.get('/api/users', [() => import('#controllers/assembly_forum_controller'), 'listUsers'])
  router.get('/api/users/by-alias/:userAlias', [() => import('#controllers/assembly_forum_controller'), 'getUserByAlias'])
  router.get('/api/users/:id', [() => import('#controllers/assembly_forum_controller'), 'getUser'])
  router.post('/api/users', [() => import('#controllers/assembly_forum_controller'), 'createUser'])
  // bridges
  router.post('/api/bridges/forum-agenda', [() => import('#controllers/assembly_bridge_controller'), 'linkForumAgenda'])
  router.delete('/api/bridges/forum-agenda', [() => import('#controllers/assembly_bridge_controller'), 'unlinkForumAgenda'])
  router.get('/api/bridges/forums-by-agenda/:agendaId', [() => import('#controllers/assembly_bridge_controller'), 'forumsByAgenda'])
  router.get('/api/bridges/agendas-by-forum/:forumId', [() => import('#controllers/assembly_bridge_controller'), 'agendasByForum'])
  router.post('/api/bridges/post-artifact', [() => import('#controllers/assembly_bridge_controller'), 'linkPostArtifact'])
  router.delete('/api/bridges/post-artifact', [() => import('#controllers/assembly_bridge_controller'), 'unlinkPostArtifact'])
  router.get('/api/bridges/artifact-threads/:type/:id', [() => import('#controllers/assembly_bridge_controller'), 'artifactThreads'])
  router.get('/api/bridges/artifact-refs/:postId', [() => import('#controllers/assembly_bridge_controller'), 'artifactRefs'])
  router.post('/api/bridges/supporting-refs', [() => import('#controllers/assembly_bridge_controller'), 'addSupportingRef'])
  router.get('/api/bridges/supporting-refs/post/:postId', [() => import('#controllers/assembly_bridge_controller'), 'supportingRefsByPost'])
  router.get('/api/bridges/supporting-refs/comment/:commentId', [() => import('#controllers/assembly_bridge_controller'), 'supportingRefsByComment'])
  // duality
  router.post('/api/duality/watches', [() => import('#controllers/assembly_bridge_controller'), 'createWatch'])
  router.get('/api/duality/watches/active', [() => import('#controllers/assembly_bridge_controller'), 'activeWatch'])
  router.get('/api/duality/watches/:threadId', [() => import('#controllers/assembly_bridge_controller'), 'threadWatches'])
})

// ── voyager-srv (re-homed Wave 2.4) ───────────────────────────────────
// Registered BEFORE the semantics generic :table wildcards so the literal
// /api/entities, /api/spans, /api/scan-epochs routes win the match.
router.group(() => {
  router.get('/api/health', [() => import('#controllers/voyager_controller'), 'health'])
  router.get('/api/scan-epochs', [() => import('#controllers/voyager_controller'), 'scanEpochs'])
  router.get('/api/scan-epochs/:id', [() => import('#controllers/voyager_controller'), 'scanEpoch'])
  router.get('/api/observations/files', [() => import('#controllers/voyager_controller'), 'fileObservations'])
  router.get('/api/observations/files/by-id/:observationId', [() => import('#controllers/voyager_controller'), 'fileObservationByObsId'])
  router.get('/api/observations/files/:id', [() => import('#controllers/voyager_controller'), 'fileObservation'])
  router.get('/api/observations/directories', [() => import('#controllers/voyager_controller'), 'directoryObservations'])
  router.get('/api/topology/signals', [() => import('#controllers/voyager_controller'), 'topologySignals'])
  router.get('/api/topology/signals/:id', [() => import('#controllers/voyager_controller'), 'topologySignal'])
  router.get('/api/topology/edge-hints', [() => import('#controllers/voyager_controller'), 'edgeHints'])
  router.get('/api/entities', [() => import('#controllers/voyager_controller'), 'entities'])
  router.get('/api/entities/by-id/:entityId', [() => import('#controllers/voyager_controller'), 'entityByEntityId'])
  router.get('/api/entities/:id', [() => import('#controllers/voyager_controller'), 'entity'])
  router.get('/api/spans', [() => import('#controllers/voyager_controller'), 'spans'])
  router.get('/api/spans/:id', [() => import('#controllers/voyager_controller'), 'span'])
  router.get('/api/stats', [() => import('#controllers/voyager_controller'), 'stats'])
})

// ── nebula-srv (re-homed Wave 3.1) — canonical data-plane surface ────────
// Registered BEFORE the semantics generic :table wildcards below so the
// literal /api/* routes win the match. SQL runs on the named `nebula`
// connection (searchPath nebula,public) with $n→? conversion in
// nebula_helpers. Knowledge entity/edge/summary/cross-reference paths are
// already served by knowledge_controller (Wave 2.1); only the nebula-unique
// /knowledge/view + /op-registry routes register here.
router.group(() => {
  router.get('/api/systems', [() => import('#controllers/nebula_hierarchy_controller'), 'listSystems'])
  router.post('/api/systems', [() => import('#controllers/nebula_hierarchy_controller'), 'createSystem'])
  router.patch('/api/systems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'updateSystem'])
  router.delete('/api/systems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteSystem'])
  router.get('/api/systems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'getSystem'])
  router.post('/api/subsystems', [() => import('#controllers/nebula_hierarchy_controller'), 'createSubsystem'])
  router.patch('/api/subsystems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'updateSubsystem'])
  router.delete('/api/subsystems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteSubsystem'])
  router.get('/api/subsystems/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'getSubsystem'])
  router.post('/api/features', [() => import('#controllers/nebula_hierarchy_controller'), 'createFeature'])
  router.patch('/api/features/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'updateFeature'])
  router.delete('/api/features/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteFeature'])
  router.get('/api/features/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'getFeature'])
  router.get('/api/requirements', [() => import('#controllers/nebula_hierarchy_controller'), 'listRequirements'])
  router.get('/api/requirements/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'getRequirement'])
  router.get('/api/requirements/:id/children', [() => import('#controllers/nebula_hierarchy_controller'), 'requirementChildren'])
  router.get('/api/requirements/:id/dependencies', [() => import('#controllers/nebula_hierarchy_controller'), 'requirementDependencies'])
  router.post('/api/requirements/:id/dependencies', [() => import('#controllers/nebula_hierarchy_controller'), 'createRequirementDependency'])
  router.delete('/api/requirements/:id/dependencies/:depId', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteRequirementDependency'])
  router.post('/api/requirements', [() => import('#controllers/nebula_hierarchy_controller'), 'createRequirement'])
  router.patch('/api/requirements/batch', [() => import('#controllers/nebula_hierarchy_controller'), 'batchUpdateRequirements'])
  router.patch('/api/requirements/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'updateRequirement'])
  router.delete('/api/requirements/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteRequirement'])
  router.post('/api/requirements/:id/move', [() => import('#controllers/nebula_hierarchy_controller'), 'moveRequirement'])
  router.post('/api/requirements/:id/compile', [() => import('#controllers/nebula_hierarchy_controller'), 'compileRequirement'])
  router.post('/api/systems/:id/folders', [() => import('#controllers/nebula_hierarchy_controller'), 'createSystemFolder'])
  router.delete('/api/systems/:systemId/folders/:folderId', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteSystemFolder'])
  router.get('/api/sessions', [() => import('#controllers/nebula_hierarchy_controller'), 'listSessions'])
  router.post('/api/sessions', [() => import('#controllers/nebula_hierarchy_controller'), 'createSession'])
  router.patch('/api/sessions/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'updateSession'])
  router.post('/api/features/move', [() => import('#controllers/nebula_hierarchy_controller'), 'moveFeature'])
  router.post('/api/subsystems/move', [() => import('#controllers/nebula_hierarchy_controller'), 'moveSubsystem'])
  router.post('/api/systems/demote/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'demoteSystem'])
  router.delete('/api/sessions/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteSession'])
  router.get('/api/workspaces', [() => import('#controllers/nebula_hierarchy_controller'), 'listWorkspaces'])
  router.post('/api/workspaces', [() => import('#controllers/nebula_hierarchy_controller'), 'createWorkspace'])
  router.delete('/api/workspaces/:id', [() => import('#controllers/nebula_hierarchy_controller'), 'deleteWorkspace'])
  router.get('/api/docs', [() => import('#controllers/nebula_docs_controller'), 'docs'])
  router.get('/api/subsystems/:id/docs', [() => import('#controllers/nebula_docs_controller'), 'subsystemDocs'])
  router.get('/api/systems/:id/docs', [() => import('#controllers/nebula_docs_controller'), 'systemDocs'])
  router.get('/api/plans', [() => import('#controllers/nebula_docs_controller'), 'listPlans'])
  router.get('/api/plans/:id', [() => import('#controllers/nebula_docs_controller'), 'getPlan'])
  router.post('/api/plans', [() => import('#controllers/nebula_docs_controller'), 'createPlan'])
  router.get('/api/implementation-plans/statuses', [() => import('#controllers/nebula_docs_controller'), 'planStatuses'])
  router.get('/api/systems/:id/implementation-plans', [() => import('#controllers/nebula_docs_controller'), 'systemPlans'])
  router.get('/api/subsystems/:id/implementation-plans', [() => import('#controllers/nebula_docs_controller'), 'subsystemPlans'])
  router.get('/api/features/:id/implementation-plans', [() => import('#controllers/nebula_docs_controller'), 'featurePlans'])
  router.get('/api/audit', [() => import('#controllers/nebula_docs_controller'), 'listAudit'])
  router.get('/api/audit/graph', [() => import('#controllers/nebula_docs_controller'), 'auditGraph'])
  router.get('/api/audit/:id', [() => import('#controllers/nebula_docs_controller'), 'getAuditFile'])
  router.post('/api/audit/sync', [() => import('#controllers/nebula_docs_controller'), 'syncAudit'])
  router.post('/api/audit/:id/regenerate', [() => import('#controllers/nebula_docs_controller'), 'regenerateAuditFile'])
  router.get('/api/preferences', [() => import('#controllers/nebula_docs_controller'), 'getPreferences'])
  router.put('/api/preferences/:key', [() => import('#controllers/nebula_docs_controller'), 'setPreference'])
  router.delete('/api/preferences/:key', [() => import('#controllers/nebula_docs_controller'), 'deletePreference'])
  router.get('/api/systems/:id/info', [() => import('#controllers/nebula_docs_controller'), 'listInfoTabs'])
  router.put('/api/systems/:id/info/:tabId', [() => import('#controllers/nebula_docs_controller'), 'saveInfoTab'])
  router.delete('/api/systems/:id/info/:tabId', [() => import('#controllers/nebula_docs_controller'), 'deleteInfoTab'])
  router.post('/api/import', [() => import('#controllers/nebula_docs_controller'), 'importData'])
  router.post('/api/seed', [() => import('#controllers/nebula_docs_controller'), 'seed'])
  router.get('/api/harvests', [() => import('#controllers/nebula_harvest_controller'), 'listHarvests'])
  router.get('/api/harvests/distribution', [() => import('#controllers/nebula_harvest_controller'), 'harvestDistribution'])
  router.get('/api/harvests/:id', [() => import('#controllers/nebula_harvest_controller'), 'getHarvest'])
  router.get('/api/harvests/:id/transcript', [() => import('#controllers/nebula_harvest_controller'), 'harvestTranscript'])
  router.post('/api/harvest-candidates/:id/promote', [() => import('#controllers/nebula_harvest_controller'), 'promoteCandidate'])
  router.post('/api/harvest-candidates/promote-to-plan', [() => import('#controllers/nebula_harvest_controller'), 'promoteToPlan'])
  router.post('/api/harvests', [() => import('#controllers/nebula_harvest_controller'), 'createHarvest'])
  router.delete('/api/harvests/:id', [() => import('#controllers/nebula_harvest_controller'), 'deleteHarvest'])
  router.get('/api/plans/:planRef/candidates', [() => import('#controllers/nebula_harvest_controller'), 'planCandidates'])
  router.get('/api/systems/:id/harvest-candidates', [() => import('#controllers/nebula_harvest_controller'), 'systemHarvestCandidates'])
  router.get('/api/subsystems/:id/harvest-candidates', [() => import('#controllers/nebula_harvest_controller'), 'subsystemHarvestCandidates'])
  router.get('/api/features/:id/harvest-candidates', [() => import('#controllers/nebula_harvest_controller'), 'featureHarvestCandidates'])
  router.get('/api/intent-records', [() => import('#controllers/nebula_harvest_controller'), 'listIntentRecords'])
  router.get('/api/systems/:id/intent-records', [() => import('#controllers/nebula_harvest_controller'), 'systemIntentRecords'])
  router.get('/api/subsystems/:id/intent-records', [() => import('#controllers/nebula_harvest_controller'), 'subsystemIntentRecords'])
  router.get('/api/features/:id/intent-records', [() => import('#controllers/nebula_harvest_controller'), 'featureIntentRecords'])
  router.get('/api/intent-records/:id', [() => import('#controllers/nebula_harvest_controller'), 'getIntentRecord'])
  router.get('/api/agendas', [() => import('#controllers/nebula_harvest_controller'), 'listAgendas'])
  router.get('/api/agendas/:id', [() => import('#controllers/nebula_harvest_controller'), 'getAgenda'])
  router.get('/api/systems/:id/agendas', [() => import('#controllers/nebula_harvest_controller'), 'systemAgendas'])
  router.get('/api/subsystems/:id/agendas', [() => import('#controllers/nebula_harvest_controller'), 'subsystemAgendas'])
  router.get('/api/features/:id/agendas', [() => import('#controllers/nebula_harvest_controller'), 'featureAgendas'])
  router.delete('/api/agendas/:id/items', [() => import('#controllers/nebula_harvest_controller'), 'deleteAgendaItem'])
  router.post('/api/agendas/:id/finalize', [() => import('#controllers/nebula_harvest_controller'), 'finalizeAgenda'])
  router.post('/api/agendas/:id/items', [() => import('#controllers/nebula_harvest_controller'), 'addAgendaItem'])
  router.get('/api/specifications', [() => import('#controllers/nebula_harvest_controller'), 'listSpecifications'])
  router.get('/api/specifications/:id', [() => import('#controllers/nebula_harvest_controller'), 'getSpecification'])
  router.get('/api/systems/:id/specifications', [() => import('#controllers/nebula_harvest_controller'), 'systemSpecifications'])
  router.get('/api/subsystems/:id/specifications', [() => import('#controllers/nebula_harvest_controller'), 'subsystemSpecifications'])
  router.get('/api/features/:id/specifications', [() => import('#controllers/nebula_harvest_controller'), 'featureSpecifications'])
  router.get('/api/work-requests', [() => import('#controllers/nebula_harvest_controller'), 'listWorkRequests'])
  router.get('/api/work-requests/:id', [() => import('#controllers/nebula_harvest_controller'), 'getWorkRequest'])
  router.get('/api/systems/:id/work-requests', [() => import('#controllers/nebula_harvest_controller'), 'systemWorkRequests'])
  router.get('/api/subsystems/:id/work-requests', [() => import('#controllers/nebula_harvest_controller'), 'subsystemWorkRequests'])
  router.get('/api/features/:id/work-requests', [() => import('#controllers/nebula_harvest_controller'), 'featureWorkRequests'])
  router.get('/api/harvest-candidates', [() => import('#controllers/nebula_harvest_controller'), 'listHarvestCandidates'])
  router.get('/api/harvest-candidates/:id', [() => import('#controllers/nebula_harvest_controller'), 'getHarvestCandidate'])
  router.get('/api/candidates', [() => import('#controllers/nebula_harvest_controller'), 'listCandidatesAlias'])
  router.get('/api/candidates/:id', [() => import('#controllers/nebula_harvest_controller'), 'getCandidateAlias'])
  router.patch('/api/harvest-candidates/:id', [() => import('#controllers/nebula_harvest_controller'), 'updateHarvestCandidate'])
  router.post('/api/harvest-candidates/:id/spawn-plan', [() => import('#controllers/nebula_harvest_controller'), 'spawnPlan'])
  router.post('/api/harvest-candidates', [() => import('#controllers/nebula_harvest_controller'), 'createHarvestCandidate'])
  router.post('/api/specifications/:id/link-requirements', [() => import('#controllers/nebula_harvest_controller'), 'linkSpecRequirements'])
  router.get('/api/specs', [() => import('#controllers/nebula_harvest_controller'), 'listSpecs'])
  router.get('/api/specs/:id', [() => import('#controllers/nebula_harvest_controller'), 'getSpec'])
  router.post('/api/harvest-candidates/discover', [() => import('#controllers/nebula_harvest_controller'), 'discoverCandidates'])
  router.get('/api/agent-records', [() => import('#controllers/nebula_records_controller'), 'listAgentRecords'])
  router.get('/api/agent-records/:id', [() => import('#controllers/nebula_records_controller'), 'getAgentRecord'])
  router.post('/api/agent-records/search', [() => import('#controllers/nebula_records_controller'), 'searchAgentRecords'])
  router.post('/api/agent-records', [() => import('#controllers/nebula_records_controller'), 'createAgentRecord'])
  router.patch('/api/agent-records/:id', [() => import('#controllers/nebula_records_controller'), 'updateAgentRecord'])
  router.delete('/api/agent-records/:id', [() => import('#controllers/nebula_records_controller'), 'deleteAgentRecord'])
  router.get('/api/inbox-pointer/:role', [() => import('#controllers/nebula_records_controller'), 'getInboxPointer'])
  router.put('/api/inbox-pointer/:role', [() => import('#controllers/nebula_records_controller'), 'setInboxPointer'])
  router.get('/api/inbox-pointers', [() => import('#controllers/nebula_records_controller'), 'listInboxPointers'])
  router.get('/api/projections', [() => import('#controllers/nebula_records_controller'), 'listProjections'])
  router.post('/api/projections', [() => import('#controllers/nebula_records_controller'), 'createProjection'])
  router.post('/api/projections/:id/render', [() => import('#controllers/nebula_records_controller'), 'renderProjection'])
  router.delete('/api/projections/:id', [() => import('#controllers/nebula_records_controller'), 'deleteProjection'])
  router.post('/api/cross-references', [() => import('#controllers/nebula_records_controller'), 'createCrossReference'])
  router.get('/api/cross-references', [() => import('#controllers/nebula_records_controller'), 'listCrossReferences'])
  router.get('/api/cross-references/:id', [() => import('#controllers/nebula_records_controller'), 'getCrossReference'])
  router.delete('/api/cross-references/:id', [() => import('#controllers/nebula_records_controller'), 'deleteCrossReference'])
  router.post('/api/evidence-links', [() => import('#controllers/nebula_records_controller'), 'createEvidenceLink'])
  router.get('/api/evidence-links', [() => import('#controllers/nebula_records_controller'), 'listEvidenceLinks'])
  router.get('/api/evidence-links/:id', [() => import('#controllers/nebula_records_controller'), 'getEvidenceLink'])
  router.delete('/api/evidence-links/:id', [() => import('#controllers/nebula_records_controller'), 'deleteEvidenceLink'])
  router.delete('/api/evidence-links', [() => import('#controllers/nebula_records_controller'), 'bulkDeleteEvidenceLinks'])
  router.get('/api/conversations/by-snapshot/:snapshotId', [() => import('#controllers/nebula_segmentation_controller'), 'conversationBySnapshot'])
  router.get('/api/conversations', [() => import('#controllers/nebula_segmentation_controller'), 'listConversations'])
  router.get('/api/conversations/:id/snapshots', [() => import('#controllers/nebula_segmentation_controller'), 'conversationSnapshots'])
  router.get('/api/snapshots/:id/blocks', [() => import('#controllers/nebula_segmentation_controller'), 'snapshotBlocks'])
  router.get('/api/conversations/:id/blocks', [() => import('#controllers/nebula_segmentation_controller'), 'conversationBlocks'])
  router.get('/api/conversations/by-snapshot/:snapshotId/blocks', [() => import('#controllers/nebula_segmentation_controller'), 'conversationBySnapshotBlocks'])
  router.post('/api/snapshots', [() => import('#controllers/nebula_segmentation_controller'), 'createSnapshot'])
  router.post('/api/segments', [() => import('#controllers/nebula_segmentation_controller'), 'createSegment'])
  router.patch('/api/segments/:id', [() => import('#controllers/nebula_segmentation_controller'), 'updateSegment'])
  router.delete('/api/segments/:id', [() => import('#controllers/nebula_segmentation_controller'), 'deleteSegment'])
  router.post('/api/projection-overrides', [() => import('#controllers/nebula_segmentation_controller'), 'createProjectionOverride'])
  router.delete('/api/projection-overrides/:id', [() => import('#controllers/nebula_segmentation_controller'), 'deleteProjectionOverride'])
  router.get('/api/snapshots/:id/projection', [() => import('#controllers/nebula_segmentation_controller'), 'snapshotProjection'])
  router.get('/api/snapshots/:id/references', [() => import('#controllers/nebula_segmentation_controller'), 'snapshotReferences'])
  router.get('/api/knowledge/view', [() => import('#controllers/nebula_knowledge_controller'), 'view'])
  router.post('/api/op-registry', [() => import('#controllers/nebula_knowledge_controller'), 'createOpRegistryEntry'])
  router.get('/api/op-registry', [() => import('#controllers/nebula_knowledge_controller'), 'listOpRegistry'])
  router.get('/api/op-registry/:id', [() => import('#controllers/nebula_knowledge_controller'), 'getOpRegistryEntry'])
  router.patch('/api/op-registry/:id/deprecate', [() => import('#controllers/nebula_knowledge_controller'), 'deprecateOpRegistryEntry'])
  router.patch('/api/op-registry/:id/supersede', [() => import('#controllers/nebula_knowledge_controller'), 'supersedeOpRegistryEntry'])
  router.delete('/api/op-registry/:id', [() => import('#controllers/nebula_knowledge_controller'), 'deleteOpRegistryEntry'])
  router.post('/api/op-registry/fork', [() => import('#controllers/nebula_knowledge_controller'), 'forkOpRegistryEntry'])
  router.get('/api/op-registry/:id/lineage', [() => import('#controllers/nebula_knowledge_controller'), 'opRegistryLineage'])
  router.get('/api/conduit/plans', [() => import('#controllers/nebula_conduit_controller'), 'listConduitPlans'])
  router.get('/api/conduit/plans/as-of', [() => import('#controllers/nebula_conduit_controller'), 'conduitPlansAsOf'])
  router.get('/api/conduit/plans/:id/history', [() => import('#controllers/nebula_conduit_controller'), 'conduitPlanHistory'])
  router.get('/api/conduit/plans/:id/receipts', [() => import('#controllers/nebula_conduit_controller'), 'conduitPlanReceipts'])
  router.get('/api/conduit/deleted-plans', [() => import('#controllers/nebula_conduit_controller'), 'conduitDeletedPlans'])
  router.post('/api/execution/requests', [() => import('#controllers/nebula_conduit_controller'), 'createExecutionRequest'])
  router.get('/api/execution/requests', [() => import('#controllers/nebula_conduit_controller'), 'listExecutionRequests'])
  router.get('/api/execution/requests/:id', [() => import('#controllers/nebula_conduit_controller'), 'getExecutionRequest'])
  router.patch('/api/execution/requests/:id/transition', [() => import('#controllers/nebula_conduit_controller'), 'transitionExecutionRequest'])
  router.post('/api/execution/leases/acquire', [() => import('#controllers/nebula_conduit_controller'), 'acquireExecutionLease'])
  router.post('/api/execution/leases/:id/renew', [() => import('#controllers/nebula_conduit_controller'), 'renewExecutionLease'])
  router.post('/api/execution/leases/:id/release', [() => import('#controllers/nebula_conduit_controller'), 'releaseExecutionLease'])
  router.post('/api/role-leases/issue', [() => import('#controllers/nebula_conduit_controller'), 'issueRoleLease'])
  router.post('/api/role-leases/:id/renew', [() => import('#controllers/nebula_conduit_controller'), 'renewRoleLease'])
  router.post('/api/role-leases/:id/revoke', [() => import('#controllers/nebula_conduit_controller'), 'revokeRoleLease'])
  router.get('/api/role-leases', [() => import('#controllers/nebula_conduit_controller'), 'listRoleLeases'])
  router.get('/api/cascade/subscriber-status', [() => import('#controllers/nebula_conduit_controller'), 'cascadeSubscriberStatus'])
  router.get('/api/role-leases/stale', [() => import('#controllers/nebula_conduit_controller'), 'staleRoleLeases'])
  router.post('/api/role-leases/consume', [() => import('#controllers/nebula_conduit_controller'), 'consumeRoleLease'])
  router.post('/api/execution/attempts', [() => import('#controllers/nebula_conduit_controller'), 'createExecutionAttempt'])
  router.post('/api/execution/receipts', [() => import('#controllers/nebula_conduit_controller'), 'issueExecutionReceipt'])
  router.get('/api/execution/receipts', [() => import('#controllers/nebula_conduit_controller'), 'listExecutionReceipts'])
  router.get('/api/execution/state', [() => import('#controllers/nebula_conduit_controller'), 'executionState'])
  router.get('/api/open-questions', [() => import('#controllers/nebula_meta_controller'), 'listOpenQuestions'])
  router.get('/api/open-questions/:id/answers', [() => import('#controllers/nebula_meta_controller'), 'listOpenQuestionAnswers'])
  router.post('/api/open-questions/:id/answers', [() => import('#controllers/nebula_meta_controller'), 'recordOpenQuestionAnswer'])
  router.post('/api/open-questions', [() => import('#controllers/nebula_meta_controller'), 'createOpenQuestion'])
  router.put('/api/open-questions/:id/answer', [() => import('#controllers/nebula_meta_controller'), 'answerOpenQuestionLegacy'])
  router.put('/api/open-questions/:id/resolve', [() => import('#controllers/nebula_meta_controller'), 'resolveOpenQuestion'])
  router.get('/api/roles', [() => import('#controllers/nebula_meta_controller'), 'listRoles'])
  router.get('/api/roles/:id', [() => import('#controllers/nebula_meta_controller'), 'showRole'])
  router.get('/api/intents', [() => import('#controllers/nebula_meta_controller'), 'listIntents'])
  router.get('/api/intents/:id', [() => import('#controllers/nebula_meta_controller'), 'showIntent'])
  router.get('/api/assessments', [() => import('#controllers/nebula_meta_controller'), 'listAssessments'])
  router.get('/api/assessments/:id', [() => import('#controllers/nebula_meta_controller'), 'showAssessment'])
  router.get('/api/observations', [() => import('#controllers/nebula_meta_controller'), 'listObservations'])
  router.get('/api/observations/:id', [() => import('#controllers/nebula_meta_controller'), 'showObservation'])
  router.get('/api/open-questions/:id', [() => import('#controllers/nebula_meta_controller'), 'showOpenQuestion'])
  router.get('/api/open-questions/:id/timeline', [() => import('#controllers/nebula_meta_controller'), 'openQuestionTimeline'])
  router.get('/api/open-questions/:id/participants', [() => import('#controllers/nebula_meta_controller'), 'listOpenQuestionParticipants'])
  router.post('/api/open-questions/:id/participants', [() => import('#controllers/nebula_meta_controller'), 'addOpenQuestionParticipant'])
  router.get('/api/harvest-candidates/:id/dependencies', [() => import('#controllers/nebula_meta_controller'), 'candidateDependencies'])
  router.get('/api/search', [() => import('#controllers/nebula_meta_controller'), 'search'])
  router.get('/api/counts', [() => import('#controllers/nebula_meta_controller'), 'counts'])
  router.get('/api/architect-specs', [() => import('#controllers/nebula_meta_controller'), 'listArchitectSpecs'])
  router.get('/api/architect-specs/:id', [() => import('#controllers/nebula_meta_controller'), 'showArchitectSpec'])
  router.post('/api/architect-specs', [() => import('#controllers/nebula_meta_controller'), 'createArchitectSpec'])
  router.delete('/api/architect-specs/:id', [() => import('#controllers/nebula_meta_controller'), 'deleteArchitectSpec'])
  router.get('/api/artifact-provenance', [() => import('#controllers/nebula_meta_controller'), 'listArtifactProvenance'])
  router.get('/api/artifact-provenance/:id', [() => import('#controllers/nebula_meta_controller'), 'showArtifactProvenance'])
  router.post('/api/artifact-provenance', [() => import('#controllers/nebula_meta_controller'), 'createArtifactProvenance'])
  router.delete('/api/artifact-provenance/:id', [() => import('#controllers/nebula_meta_controller'), 'deleteArtifactProvenance'])
  router.post('/api/search/semantic', [() => import('#controllers/nebula_meta_controller'), 'semanticSearch'])
  router.get('/api/cpf', [() => import('#controllers/nebula_meta_controller'), 'cpf'])
  router.get('/api/cpf/count', [() => import('#controllers/nebula_meta_controller'), 'cpfCount'])
  router.post('/api/cpf/promote', [() => import('#controllers/nebula_meta_controller'), 'cpfPromote'])
  router.post('/api/refresh-stats', [() => import('#controllers/nebula_meta_controller'), 'refreshStats'])
  router.get('/api/systems/:id/inventory', [() => import('#controllers/nebula_meta_controller'), 'systemInventory'])
  router.get('/api/inventory', [() => import('#controllers/nebula_meta_controller'), 'inventory'])
  router.get('/api/systems/:id/external-ids', [() => import('#controllers/nebula_meta_controller'), 'systemExternalIds'])
  router.post('/api/systems/:id/external-ids', [() => import('#controllers/nebula_meta_controller'), 'createSystemExternalId'])
  router.delete('/api/systems/:id/external-ids/:eid', [() => import('#controllers/nebula_meta_controller'), 'deleteSystemExternalId'])
  router.get('/api/external-ids', [() => import('#controllers/nebula_meta_controller'), 'externalIds'])
  router.patch('/api/external-ids/:id', [() => import('#controllers/nebula_meta_controller'), 'patchExternalId'])
})

// ── semantics-srv generic per-table CRUD (registered last so the literal
//    special + voyager /api/* routes win the match). ──────────────────
router.group(() => {
  router.get('/api/:table', [() => import('#controllers/semantics_controller'), 'listTable'])
  router.get('/api/:table/:id', [() => import('#controllers/semantics_controller'), 'getTableRow'])
  router.post('/api/:table', [() => import('#controllers/semantics_controller'), 'addTableRow'])
  router.patch('/api/:table/:id', [() => import('#controllers/semantics_controller'), 'updateTableRow'])
  router.delete('/api/:table/:id', [() => import('#controllers/semantics_controller'), 'softDeleteTableRow'])
})

// ── terrain-srv (re-homed Wave 2.3) ───────────────────────────────────
router.group(() => {
  router.get('/terrain/servers', [() => import('#controllers/terrain_controller'), 'servers'])
  router.get('/terrain/mcp-servers', [() => import('#controllers/terrain_controller'), 'mcpServers'])
  router.post('/terrain/mcp-servers', [() => import('#controllers/terrain_controller'), 'registerMcpServer'])
  router.get('/terrain/runnable-services', [() => import('#controllers/terrain_controller'), 'runnableServices'])
  router.post('/terrain/runnable-services', [() => import('#controllers/terrain_controller'), 'registerRunnableService'])
  router.get('/terrain/cli-tools', [() => import('#controllers/terrain_controller'), 'cliTools'])
  router.post('/terrain/cli-tools', [() => import('#controllers/terrain_controller'), 'registerCliTool'])
  router.get('/terrain/services/:name', [() => import('#controllers/terrain_controller'), 'serviceLookup'])
  router.get('/terrain/services/:name/running', [() => import('#controllers/terrain_controller'), 'serviceRunning'])
  router.patch('/terrain/services/status', [() => import('#controllers/terrain_controller'), 'setServiceStatus'])
  router.get('/terrain/dependencies', [() => import('#controllers/terrain_controller'), 'dependencies'])
  router.post('/terrain/dependencies', [() => import('#controllers/terrain_controller'), 'registerDependency'])
  router.get('/terrain/summary', [() => import('#controllers/terrain_controller'), 'summary'])
})

// ── tools-aggregator ──────────────────────────────────────────────────
// Landed in Wave 2 (stateless migration). Route table is frozen by the
// TypeSpec contract (typespec/v1/tools-aggregator/); uncomment the group
// and add tools_controller when the migration is executed.
// router
//   .group(() => {
//     router.get('/tools', [() => import('#controllers/tools_controller'), 'index'])
//     router.get('/tools/:name', [() => import('#controllers/tools_controller'), 'show'])
//     router.get('/tools/by-service/:service', [() => import('#controllers/tools_controller'), 'byService'])
//     router.post('/tools/call', [() => import('#controllers/tools_controller'), 'call'])
//     router.get('/registry', [() => import('#controllers/tools_controller'), 'registry'])
//     router.post('/init', [() => import('#controllers/tools_controller'), 'init'])
//   })

// ── semantics-srv: SOL IR surface ─────────────────────────────────────
// Landed in Wave 2. Contract: typespec/v1/semantics-srv/ (to be modeled).
// router
//   .group(() => {
//     router.get('/api/meta', [() => import('#controllers/semantics_controller'), 'meta'])
//     router.get('/api/evidence_item', [() => import('#controllers/semantics_controller'), 'evidence'])
//     router.get('/api/statement_evidence', [() => import('#controllers/semantics_controller'), 'statementEvidence'])//   })
// ── knowledge-srv, terrain-srv, voyager-srv, tackle-srv, role-memory-srv ──
// Re-homed in later steps; stub route groups land with each migration so the
// conformance validator only sees declared routes.
