spring.application.name=terrain
server.port=8084

# PostgreSQL (schema: terrain)
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus?currentSchema=terrain
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pguser
spring.datasource.password=pgpass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORS
allowed.origins=*

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
