-- Atlas V2: Add second camera viewpoint columns to graph_views

ALTER TABLE registry.graph_views
    ADD COLUMN IF NOT EXISTS camera2_position_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS camera2_position_y DOUBLE PRECISION NOT NULL DEFAULT 40,
    ADD COLUMN IF NOT EXISTS camera2_position_z DOUBLE PRECISION NOT NULL DEFAULT 120,
    ADD COLUMN IF NOT EXISTS camera2_target_x   DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS camera2_target_y   DOUBLE PRECISION NOT NULL DEFAULT 15,
    ADD COLUMN IF NOT EXISTS camera2_target_z   DOUBLE PRECISION NOT NULL DEFAULT 0;
