import { Router } from 'express';
import { forumsRouter } from './forums.js';
import { feedRouter } from './feed.js';
import { workRequestsRouter } from './work-requests.js';
import { requirementsRouter } from './requirements.js';
import { agendasRouter } from './agendas.js';
import { candidatesRouter } from './candidates.js';
import { harvestsRouter } from './harvests.js';
import { conversationsRouter } from './conversations.js';
import { openQuestionsRouter } from './open-questions.js';
import { intentsRouter } from './intents.js';
import { assessmentsRouter } from './assessments.js';
import { observationsRouter } from './observations.js';
import { reportsRouter } from './reports.js';
import { agentRecordsRouter } from './agent-records.js';
import { specificationsRouter } from './specifications.js';
import { usersRouter } from './users.js';
import { specsRouter } from './specs.js';
import { countsRouter } from './counts.js';
import { searchRouter } from './search.js';

export const routes = Router();

routes.use('/counts', countsRouter);
routes.use('/search', searchRouter);
routes.use('/forums', forumsRouter);
routes.use('/feed', feedRouter);
routes.use('/work-requests', workRequestsRouter);
routes.use('/requirements', requirementsRouter);
routes.use('/agendas', agendasRouter);
routes.use('/candidates', candidatesRouter);
routes.use('/harvests', harvestsRouter);
routes.use('/conversations', conversationsRouter);
routes.use('/open-questions', openQuestionsRouter);
routes.use('/intents', intentsRouter);
routes.use('/assessments', assessmentsRouter);
routes.use('/observations', observationsRouter);
routes.use('/reports', reportsRouter);
routes.use('/agent-records', agentRecordsRouter);
routes.use('/specifications', specificationsRouter);
routes.use('/users', usersRouter);
routes.use('/specs', specsRouter);
