/**
 * Unit tests for src/emit-sql.ts — renderSql over hand-built Catalogs.
 *
 * The SQL shape is a contract with the 0005 database API: ordered field
 * get-or-creates, topologically ordered stereotype_create_revision calls
 * (parent = parent's head via stereotype_resolve), optional instance-
 * storage registrations OUTSIDE the contract, and a verification echo —
 * all inside one BEGIN/COMMIT so the deferred triggers arbitrate the
 * whole migration at COMMIT (the scrap-DB oracle property, PR #591).
 *
 * The materialization regression test pins the #591 oracle catch: a child
 * model must EMIT its materialized inherited required fields in the
 * create call. The pre-fix emitter emitted only the child's own
 * properties and the scrap DB rejected the migration at COMMIT with
 * `required fields {11,12} missing relative to parent revision 2` — the
 * test below fails against that shape by construction.
 */
import { describe, expect, it } from "vitest";
import { renderSql } from "../emit-sql.js";
import { createCatalog } from "../catalog.js";
import type { Catalog, RevisionRow, FieldRow } from "../catalog.js";

function field(name: string, code: number, index: number): FieldRow {
  return {
    property_name: name,
    label: name,
    name,
    field_type_code: code,
    is_calculated: false,
    field_index: index,
  };
}

function revision(partial: Partial<RevisionRow> & { stereotypeName: string }): RevisionRow {
  return {
    parentStereotypeName: undefined,
    rationale: undefined,
    fields: [],
    ...partial,
  };
}

/** Builds the post-#591-fix shape: root + child that materializes the two
 *  parent-required fields it does not redeclare (the oracle case). */
function catalogWithMaterializedChild(): Catalog {
  const c = createCatalog();
  c.stereotypes.set("Person", { name: "Person", description: "root" });
  c.stereotypes.set("VerifiedPerson", { name: "VerifiedPerson" });
  c.fields.set("givenName", field("givenName", 2, 1));
  c.fields.set("familyName", field("familyName", 2, 2));
  c.fields.set("verifiedAt", field("verifiedAt", 5, 1));
  c.revisions.push(
    revision({
      stereotypeName: "Person",
      fields: [
        { property_name: "givenName", required: true },
        { property_name: "familyName", required: true },
      ],
    }),
  );
  c.revisions.push(
    revision({
      stereotypeName: "VerifiedPerson",
      parentStereotypeName: "Person",
      rationale: "verified subtype",
      // Own property + the two MATERIALIZED parent-required fields.
      fields: [
        { property_name: "verifiedAt", required: true },
        { property_name: "givenName", required: true },
        { property_name: "familyName", required: true },
      ],
    }),
  );
  return c;
}

describe("renderSql — envelope", () => {
  it("wraps the migration in BEGIN/COMMIT (deferred-trigger atomicity)", () => {
    const sql = renderSql(createCatalog());
    expect(sql.trimStart().split("\n")[0]).toMatch(/^-- Generated by tsp-eav-emitter/);
    expect(sql).toContain("BEGIN;");
    expect(sql.trimEnd().endsWith("COMMIT;")).toBe(true);
  });

  it("always emits the verification echo as the migration's own evidence", () => {
    const sql = renderSql(createCatalog());
    expect(sql).toContain("verification echo");
    expect(sql).toContain("contract_fingerprint");
    expect(sql).toContain("inherited_fields");
  });

  it("renders an empty catalog without revision calls", () => {
    const sql = renderSql(createCatalog());
    expect(sql).not.toContain("stereotype_create_revision(");
    // No field INSERTs either — the empty-catalog migration is envelope+echo only.
    expect(sql).not.toContain("INSERT INTO shrapnel.field");
  });
});

describe("renderSql — fields", () => {
  it("emits get-or-create INSERTs with ON CONFLICT DO NOTHING", () => {
    const c = createCatalog();
    c.fields.set("givenName", field("givenName", 2, 1));
    const sql = renderSql(c);
    expect(sql).toMatch(
      /INSERT INTO shrapnel\.field \(is_calculated, field_index, label, name, property_name, field_type_code\) /,
    );
    expect(sql).toContain("ON CONFLICT (property_name) DO NOTHING;");
  });

  it("carries the field_type_code from the 0001 registry", () => {
    const c = createCatalog();
    c.fields.set("verifiedAt", field("verifiedAt", 5, 1));
    expect(renderSql(c)).toContain("1, 'verifiedAt', 'verifiedAt', 'verifiedAt', 5)");
  });

  it("escapes single quotes SQL-style (O'Brien -> O''Brien)", () => {
    const c = createCatalog();
    const f = field("familyName", 2, 1);
    f.label = "O'Brien family name";
    c.fields.set("familyName", f);
    expect(renderSql(c)).toContain("'O''Brien family name'");
    expect(renderSql(c)).not.toContain("'O'Brien");
  });
});

describe("renderSql — revisions", () => {
  it("emits revisions in catalog (topological) order", () => {
    const c = catalogWithMaterializedChild();
    const sql = renderSql(c);
    const personAt = sql.indexOf("stereotype_create_revision('Person'");
    const verifiedAt = sql.indexOf("stereotype_create_revision('VerifiedPerson'");
    expect(personAt).toBeGreaterThan(-1);
    expect(verifiedAt).toBeGreaterThan(personAt);
  });

  it("passes NULL for a root revision's parent and rationale", () => {
    const c = createCatalog();
    c.revisions.push(revision({ stereotypeName: "Person" }));
    expect(renderSql(c)).toContain(
      "SELECT shrapnel.stereotype_create_revision('Person', NULL, NULL,",
    );
  });

  it("expresses the parent as a stereotype_resolve head subselect", () => {
    const sql = renderSql(catalogWithMaterializedChild());
    expect(sql).toContain(
      "(SELECT head_revision_id FROM shrapnel.stereotype_resolve('Person'))",
    );
  });

  it("quotes a non-null rationale", () => {
    const sql = renderSql(catalogWithMaterializedChild());
    expect(sql).toContain("'verified subtype'");
  });

  it("renders required/optional text arrays and the empty-array escape", () => {
    const c = createCatalog();
    c.revisions.push(
      revision({
        stereotypeName: "Thing",
        fields: [
          { property_name: "required_a", required: true },
          { property_name: "optional_b", required: false },
        ],
      }),
    );
    const sql = renderSql(c);
    expect(sql).toContain("ARRAY['required_a']::text[], ARRAY['optional_b']::text[])");
    // And the dedicated empty-array literal exists for vacuous contracts:
    const empty = createCatalog();
    empty.revisions.push(revision({ stereotypeName: "Vacuous" }));
    expect(renderSql(empty)).toContain("ARRAY[]::text[]");
  });

  it("does not include registration INSERTs when none are present", () => {
    const sql = renderSql(catalogWithMaterializedChild());
    expect(sql).not.toContain("stereotype_instance_storage");
  });
});

describe("renderSql — @instanceStorage registrations (outside the contract)", () => {
  it("emits the registration block only when registrations exist", () => {
    const c = catalogWithMaterializedChild();
    c.storageRegistrations.push({
      stereotypeName: "VerifiedPerson",
      storage: "mongodb",
      revisionIndex: 1,
    });
    const sql = renderSql(c);
    expect(sql).toContain("instance-storage registrations (metadata, NOT contract)");
    expect(sql).toContain(
      "INSERT INTO shrapnel.stereotype_instance_storage (stereotype_name, storage_class, revision_ref)",
    );
    expect(sql).toContain("'VerifiedPerson', 'mongodb'");
    expect(sql).toContain("ON CONFLICT (stereotype_name) DO UPDATE");
    // Registrations come AFTER all revision calls (outside the contract).
    const lastRev = sql.lastIndexOf("stereotype_create_revision(");
    const reg = sql.indexOf("stereotype_instance_storage");
    expect(reg).toBeGreaterThan(lastRev);
  });
});

describe("renderSql — #591 materialization regression (the oracle catch)", () => {
  it("the child's create call declares every parent-required field", () => {
    // Pre-fix shape emitted only `verifiedAt` for VerifiedPerson; the scrap
    // DB rejected it at COMMIT: `required fields {11,12} missing relative
    // to parent revision 2`. The fixed walker materializes, so the emitted
    // required array must carry all three names.
    const sql = renderSql(catalogWithMaterializedChild());
    const call = sql
      .split("\n")
      .find((l) => l.includes("stereotype_create_revision('VerifiedPerson'"));
    expect(call).toBeDefined();
    expect(call).toContain("ARRAY['verifiedAt', 'givenName', 'familyName']::text[]");
  });

  it("field get-or-creates cover materialized inherited names too", () => {
    const sql = renderSql(catalogWithMaterializedChild());
    for (const name of ["givenName", "familyName", "verifiedAt"]) {
      expect(sql).toContain(`'${name}'`);
    }
  });
});
