-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)
-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)
-- Fingerprints, superset conformance, depth, and freeze are enforced by
-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).
BEGIN;

-- ── fields (get-or-create; type codes from the 0001 registry) ──
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'a', 'a', 'a', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'b', 'b', 'b', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'c', 'c', 'c', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'd', 'd', 'd', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'e', 'e', 'e', 2) ON CONFLICT (property_name) DO NOTHING;

-- ── stereotype revisions (topological; parent = parent's head) ──
SELECT shrapnel.stereotype_create_revision('Alpha', NULL, NULL, ARRAY['a']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('Beta', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('Alpha')), 'Extends Alpha: tier 2 of the depth demo.', ARRAY['b', 'a']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('Gamma', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('Beta')), 'Extends Beta: tier 3 of the depth demo.', ARRAY['c', 'b', 'a']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('Delta', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('Gamma')), 'Extends Gamma: tier 4 of the depth demo (depth 3, still legal).', ARRAY['d', 'c', 'b', 'a']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('Echo', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('Delta')), 'Extends Delta: tier 5 of the depth demo — depth 4, C1 violation.', ARRAY['e', 'd', 'c', 'b', 'a']::text[], ARRAY[]::text[]);

-- ── verification echo: what the catalog now holds ──
SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,
       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,
       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields
FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id
ORDER BY s.name, r.version;

COMMIT;
