-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)
-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)
-- Fingerprints, superset conformance, depth, and freeze are enforced by
-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).
BEGIN;

-- ── fields (get-or-create; type codes from the 0001 registry) ──
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Given name.', 'givenName', 'givenName', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Family name.', 'familyName', 'familyName', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'Date of birth, if recorded.', 'dateOfBirth', 'dateOfBirth', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'When verification completed.', 'verifiedAt', 'verifiedAt', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'External verification reference.', 'verificationId', 'verificationId', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Subject of the credential.', 'subjectId', 'subjectId', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Credential kind.', 'kind', 'kind', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'Credential score, if scored.', 'score', 'score', 3) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 4, 'Raw credential payload.', 'payload', 'payload', 6) ON CONFLICT (property_name) DO NOTHING;

-- ── stereotype revisions (topological; parent = parent's head) ──
SELECT shrapnel.stereotype_create_revision('Person', NULL, NULL, ARRAY['givenName', 'familyName']::text[], ARRAY['dateOfBirth']::text[]);
SELECT shrapnel.stereotype_create_revision('VerifiedPerson', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('Person')), 'Extends Person because verification is a distinct lifecycle stage with its own evidence, not a flag on the base record.', ARRAY['verifiedAt', 'verificationId', 'givenName', 'familyName']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('Credential', NULL, NULL, ARRAY['subjectId', 'kind']::text[], ARRAY['score', 'payload']::text[]);

-- ── verification echo: what the catalog now holds ──
SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,
       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,
       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields
FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id
ORDER BY s.name, r.version;

COMMIT;
