-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)
-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)
-- Fingerprints, superset conformance, depth, and freeze are enforced by
-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).
BEGIN;

-- ── fields (get-or-create; type codes from the 0001 registry) ──
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Immutable identity (nebula.work_requests.id).', 'id', 'id', 7) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Short title of the requested work.', 'title', 'title', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'Full description of what is being asked.', 'description', 'description', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 4, 'The intent this request serves (cognition over the knowledge graph).', 'intent', 'intent', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 5, 'Structured context payload accompanying the request.', 'context', 'context', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 6, 'Structured constraints the work must honor.', 'constraints', 'constraints', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 7, 'Role or account that created the request.', 'created_by', 'created_by', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 8, 'Creation time.', 'created_at', 'created_at', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 9, 'Last update time.', 'updated_at', 'updated_at', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Idempotency key, derived from work ref + head SHA (unique per request).', 'request_key', 'request_key', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Work reference being verified (PR, agent record, artifact).', 'work_ref', 'work_ref', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'Exact code head being verified.', 'head_sha', 'head_sha', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 4, 'Pre-staged evidence offered to the tester (CI runs, logs).', 'evidence', 'evidence', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 5, 'Dispatch state: pending | claimed | completed | rejected | failed.', 'state', 'state', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 6, 'Bounded invocation count.', 'attempts', 'attempts', 1) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 7, 'Fencing token for the current worker; null while pending.', 'claim_token', 'claim_token', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 8, 'Crash/retry lease expiry; null while not claimed.', 'lease_until', 'lease_until', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 9, 'Rejection or failure explanation; present only on terminal states.', 'terminal_reason', 'terminal_reason', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 10, 'V179 attestation event identity, set on completion.', 'attestation_id', 'attestation_id', 7) ON CONFLICT (property_name) DO NOTHING;

-- ── stereotype revisions (topological; parent = parent's head) ──
SELECT shrapnel.stereotype_create_revision('WorkRequest', NULL, NULL, ARRAY['id', 'title', 'description', 'intent', 'context', 'constraints', 'created_by', 'created_at', 'updated_at']::text[], ARRAY[]::text[]);
SELECT shrapnel.stereotype_create_revision('TesterAttestationRequest', (SELECT head_revision_id FROM shrapnel.stereotype_resolve('WorkRequest')), 'An attestation request is a work request whose ask is verification of a specific head; it inherits identity/attribution/lifecycle from WorkRequest and adds only the attestation-specific target, evidence, and dispatch-state fields.', ARRAY['request_key', 'work_ref', 'head_sha', 'evidence', 'state', 'attempts', 'id', 'title', 'description', 'intent', 'context', 'constraints', 'created_by', 'created_at', 'updated_at']::text[], ARRAY['claim_token', 'lease_until', 'terminal_reason', 'attestation_id']::text[]);

-- ── instance-storage registrations (metadata, NOT contract) ──
INSERT INTO shrapnel.stereotype_instance_storage (stereotype_name, storage_class, revision_ref) VALUES ('TesterAttestationRequest', 'mongodb', (SELECT id FROM shrapnel.stereotype_revision WHERE stereotype_id = (SELECT id FROM shrapnel.stereotype WHERE name = 'TesterAttestationRequest') ORDER BY version DESC LIMIT 1)) ON CONFLICT (stereotype_name) DO UPDATE SET storage_class = EXCLUDED.storage_class, revision_ref = EXCLUDED.revision_ref;

-- ── verification echo: what the catalog now holds ──
SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,
       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,
       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields
FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id
ORDER BY s.name, r.version;

COMMIT;
