-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)
-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)
-- Fingerprints, superset conformance, depth, and freeze are enforced by
-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).
BEGIN;

-- ── fields (get-or-create; type codes from the 0001 registry) ──
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Immutable request identity; doubles as the Mongo _id.', 'request_id', 'request_id', 7) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Idempotency key, derived from work ref + head SHA (unique per request; a new head gets a new request).', 'request_key', 'request_key', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'PR, agent record, or artifact reference being verified.', 'work_ref', 'work_ref', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 4, 'Exact code head being verified.', 'head_sha', 'head_sha', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 5, 'Authoring role; input to the G1 self-attestation gate.', 'requested_by', 'requested_by', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 6, 'Pre-staged evidence offered to the tester (CI runs, logs).', 'evidence', 'evidence', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 7, 'Dispatch state: pending | claimed | completed | rejected | failed.', 'state', 'state', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 8, 'Bounded invocation count.', 'attempts', 'attempts', 1) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 9, 'Request creation time.', 'created_at', 'created_at', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 10, 'Last state-transition time.', 'updated_at', 'updated_at', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 11, 'Fencing token for the current worker; null while pending.', 'claim_token', 'claim_token', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 12, 'Crash/retry lease expiry; null while not claimed.', 'lease_until', 'lease_until', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 13, 'Rejection or failure explanation; present only on terminal states.', 'terminal_reason', 'terminal_reason', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 14, 'V179 attestation event identity, set on completion.', 'attestation_id', 'attestation_id', 7) ON CONFLICT (property_name) DO NOTHING;

-- ── stereotype revisions (topological; parent = parent's head) ──
SELECT shrapnel.stereotype_create_revision('TesterAttestationRequest', NULL, NULL, ARRAY['request_id', 'request_key', 'work_ref', 'head_sha', 'requested_by', 'evidence', 'state', 'attempts', 'created_at', 'updated_at']::text[], ARRAY['claim_token', 'lease_until', 'terminal_reason', 'attestation_id']::text[]);

-- ── verification echo: what the catalog now holds ──
SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,
       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,
       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields
FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id
ORDER BY s.name, r.version;

COMMIT;
