-- Generated by tsp-eav-emitter (TypeSpec -> shrapnel EAV catalog)
-- Target API: shrapnel.stereotype_create_revision (0005_stereotype_api.sql)
-- Fingerprints, superset conformance, depth, and freeze are enforced by
-- the database at COMMIT (deferred triggers, 0004_stereotype_model.sql).
BEGIN;

-- ── fields (get-or-create; type codes from the 0001 registry) ──
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 1, 'Immutable identity (nebula.work_requests.id).', 'id', 'id', 7) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 2, 'Short title of the requested work.', 'title', 'title', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 3, 'Full description of what is being asked.', 'description', 'description', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 4, 'The intent this request serves (cognition over the knowledge graph).', 'intent', 'intent', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 5, 'Structured context payload accompanying the request.', 'context', 'context', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 6, 'Structured constraints the work must honor.', 'constraints', 'constraints', 6) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 7, 'Role or account that created the request.', 'created_by', 'created_by', 2) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 8, 'Creation time.', 'created_at', 'created_at', 5) ON CONFLICT (property_name) DO NOTHING;
INSERT INTO shrapnel.field (is_calculated, field_index, label, name, property_name, field_type_code) VALUES (false, 9, 'Last update time.', 'updated_at', 'updated_at', 5) ON CONFLICT (property_name) DO NOTHING;

-- ── stereotype revisions (topological; parent = parent's head) ──
SELECT shrapnel.stereotype_create_revision('WorkRequest', NULL, NULL, ARRAY['id', 'title', 'description', 'intent', 'context', 'constraints', 'created_by', 'created_at', 'updated_at']::text[], ARRAY[]::text[]);

-- ── verification echo: what the catalog now holds ──
SELECT s.name AS stereotype_name, r.version, r.depth, r.contract_fingerprint,
       (SELECT count(*) FROM shrapnel.stereotype_field sf WHERE sf.stereotype_revision_id = r.id) AS declared_fields,
       (SELECT count(*) FROM shrapnel.stereotype_field sf2 JOIN shrapnel.stereotype_field sf3 ON sf3.stereotype_revision_id = r.parent_revision_id AND sf2.field_id = sf3.field_id WHERE sf2.stereotype_revision_id = r.id) AS inherited_fields
FROM shrapnel.stereotype_revision r JOIN shrapnel.stereotype s ON s.id = r.stereotype_id
ORDER BY s.name, r.version;

COMMIT;
