import { Service, ServiceBroker } from "moleculer";
import ApiGateway from "moleculer-web";

/**
 * Broker HTTP gateway for the nebula-srv twin.
 *
 * Dispatch-through-Express (fleet twin pattern): the incumbent serves 231
 * registered endpoints across 182 paths (the agent-record backbone).
 * FastAPI-free, Paged<T>-shaped envelopes ({items,total,...}) pass through
 * the verbatim stack unchanged.
 *
 * NO AUTH GATE: the incumbent is CORS + express.json only — parity is the
 * contract.
 *
 * The alias map is GENERATED from typescript/nebula-srv/openapi.yaml (the
 * committed contract) — one alias per declared (method, path), so gateway
 * surface == contract surface by construction; check_drift.py holds the
 * equality from the other side. NOTE: nebula's contract paths carry the
 * /api prefix (unlike substance), matching the incumbent's app.use("/api",
 * createRoutes(pool)) mount; /health and /api/health are declared in the
 * contract and aliased here.
 */
export default class ApiService extends Service {
  constructor(broker: ServiceBroker) {
    super(broker);
    this.parseServiceSchema({
      name: "api",
      mixins: [ApiGateway],
      settings: {
        port: process.env.SERVICE_PORT || 4101,
        ip: "0.0.0.0",
        routes: [
          {
            path: "/",
            whitelist: ["nebula.**"],
            bodyParsers: { json: true },
            aliases: {
              "GET /api/agendas": "nebula.dispatch",
              "POST /api/agendas": "nebula.dispatch",
              "GET /api/agendas/:id": "nebula.dispatch",
              "POST /api/agendas/:id/finalize": "nebula.dispatch",
              "DELETE /api/agendas/:id/items": "nebula.dispatch",
              "POST /api/agendas/:id/items": "nebula.dispatch",
              "GET /api/agent-records": "nebula.dispatch",
              "POST /api/agent-records": "nebula.dispatch",
              "DELETE /api/agent-records/:id": "nebula.dispatch",
              "GET /api/agent-records/:id": "nebula.dispatch",
              "PATCH /api/agent-records/:id": "nebula.dispatch",
              "POST /api/agent-records/search": "nebula.dispatch",
              "GET /api/architect-specs": "nebula.dispatch",
              "POST /api/architect-specs": "nebula.dispatch",
              "DELETE /api/architect-specs/:id": "nebula.dispatch",
              "GET /api/architect-specs/:id": "nebula.dispatch",
              "GET /api/artifact-provenance": "nebula.dispatch",
              "POST /api/artifact-provenance": "nebula.dispatch",
              "DELETE /api/artifact-provenance/:id": "nebula.dispatch",
              "GET /api/artifact-provenance/:id": "nebula.dispatch",
              "GET /api/assessments": "nebula.dispatch",
              "GET /api/assessments/:id": "nebula.dispatch",
              "GET /api/attestations": "nebula.dispatch",
              "GET /api/audit": "nebula.dispatch",
              "GET /api/audit/:id": "nebula.dispatch",
              "POST /api/audit/:id/regenerate": "nebula.dispatch",
              "GET /api/audit/graph": "nebula.dispatch",
              "POST /api/audit/sync": "nebula.dispatch",
              "GET /api/candidates": "nebula.dispatch",
              "GET /api/candidates/:id": "nebula.dispatch",
              "GET /api/cascade/subscriber-status": "nebula.dispatch",
              "GET /api/conduit/deleted-plans": "nebula.dispatch",
              "GET /api/conduit/plans": "nebula.dispatch",
              "GET /api/conduit/plans/:id/history": "nebula.dispatch",
              "GET /api/conduit/plans/:id/receipts": "nebula.dispatch",
              "GET /api/conduit/plans/as-of": "nebula.dispatch",
              "GET /api/conversations": "nebula.dispatch",
              "GET /api/conversations/:id/blocks": "nebula.dispatch",
              "GET /api/conversations/:id/snapshots": "nebula.dispatch",
              "GET /api/conversations/by-snapshot/:snapshotId": "nebula.dispatch",
              "GET /api/conversations/by-snapshot/:snapshotId/blocks": "nebula.dispatch",
              "GET /api/counts": "nebula.dispatch",
              "GET /api/cpf": "nebula.dispatch",
              "GET /api/cpf/count": "nebula.dispatch",
              "POST /api/cpf/promote": "nebula.dispatch",
              "GET /api/cross-references": "nebula.dispatch",
              "POST /api/cross-references": "nebula.dispatch",
              "DELETE /api/cross-references/:id": "nebula.dispatch",
              "GET /api/cross-references/:id": "nebula.dispatch",
              "GET /api/docs": "nebula.dispatch",
              "DELETE /api/evidence-links": "nebula.dispatch",
              "GET /api/evidence-links": "nebula.dispatch",
              "POST /api/evidence-links": "nebula.dispatch",
              "DELETE /api/evidence-links/:id": "nebula.dispatch",
              "GET /api/evidence-links/:id": "nebula.dispatch",
              "POST /api/execution/attempts": "nebula.dispatch",
              "POST /api/execution/leases/:id/release": "nebula.dispatch",
              "POST /api/execution/leases/:id/renew": "nebula.dispatch",
              "POST /api/execution/leases/acquire": "nebula.dispatch",
              "GET /api/execution/receipts": "nebula.dispatch",
              "POST /api/execution/receipts": "nebula.dispatch",
              "GET /api/execution/requests": "nebula.dispatch",
              "POST /api/execution/requests": "nebula.dispatch",
              "GET /api/execution/requests/:id": "nebula.dispatch",
              "PATCH /api/execution/requests/:id/transition": "nebula.dispatch",
              "GET /api/execution/state": "nebula.dispatch",
              "GET /api/external-ids": "nebula.dispatch",
              "PATCH /api/external-ids/:id": "nebula.dispatch",
              "POST /api/features": "nebula.dispatch",
              "DELETE /api/features/:id": "nebula.dispatch",
              "GET /api/features/:id": "nebula.dispatch",
              "PATCH /api/features/:id": "nebula.dispatch",
              "GET /api/features/:id/agendas": "nebula.dispatch",
              "GET /api/features/:id/harvest-candidates": "nebula.dispatch",
              "GET /api/features/:id/implementation-plans": "nebula.dispatch",
              "GET /api/features/:id/specifications": "nebula.dispatch",
              "GET /api/features/:id/work-requests": "nebula.dispatch",
              "POST /api/features/move": "nebula.dispatch",
              "GET /api/harvest-candidates": "nebula.dispatch",
              "POST /api/harvest-candidates": "nebula.dispatch",
              "GET /api/harvest-candidates/:id": "nebula.dispatch",
              "PATCH /api/harvest-candidates/:id": "nebula.dispatch",
              "GET /api/harvest-candidates/:id/completion": "nebula.dispatch",
              "GET /api/harvest-candidates/:id/dependencies": "nebula.dispatch",
              "POST /api/harvest-candidates/:id/promote": "nebula.dispatch",
              "GET /api/harvest-candidates/:id/segment-sets": "nebula.dispatch",
              "POST /api/harvest-candidates/:id/spawn-plan": "nebula.dispatch",
              "POST /api/harvest-candidates/:id/spawn-requirement": "nebula.dispatch",
              "POST /api/harvest-candidates/completion-sweep": "nebula.dispatch",
              "POST /api/harvest-candidates/discover": "nebula.dispatch",
              "POST /api/harvest-candidates/promote-to-plan": "nebula.dispatch",
              "GET /api/harvests": "nebula.dispatch",
              "POST /api/harvests": "nebula.dispatch",
              "DELETE /api/harvests/:id": "nebula.dispatch",
              "GET /api/harvests/:id": "nebula.dispatch",
              "GET /api/harvests/:id/transcript": "nebula.dispatch",
              "GET /api/harvests/distribution": "nebula.dispatch",
              "GET /api/health": "nebula.dispatch",
              "GET /api/implementation-plans/statuses": "nebula.dispatch",
              "POST /api/import": "nebula.dispatch",
              "GET /api/inbox-pointer/:role": "nebula.dispatch",
              "PUT /api/inbox-pointer/:role": "nebula.dispatch",
              "GET /api/inbox-pointers": "nebula.dispatch",
              "GET /api/inventory": "nebula.dispatch",
              "GET /api/knowledge/cross-references": "nebula.dispatch",
              "GET /api/knowledge/edges": "nebula.dispatch",
              "GET /api/knowledge/entities": "nebula.dispatch",
              "GET /api/knowledge/entities/:section/:entityId": "nebula.dispatch",
              "GET /api/knowledge/entities/:section/:entityId/relations": "nebula.dispatch",
              "GET /api/knowledge/summary": "nebula.dispatch",
              "GET /api/knowledge/view": "nebula.dispatch",
              "GET /api/observations": "nebula.dispatch",
              "GET /api/observations/:id": "nebula.dispatch",
              "GET /api/op-registry": "nebula.dispatch",
              "POST /api/op-registry": "nebula.dispatch",
              "DELETE /api/op-registry/:id": "nebula.dispatch",
              "GET /api/op-registry/:id": "nebula.dispatch",
              "PATCH /api/op-registry/:id/deprecate": "nebula.dispatch",
              "GET /api/op-registry/:id/lineage": "nebula.dispatch",
              "PATCH /api/op-registry/:id/supersede": "nebula.dispatch",
              "POST /api/op-registry/fork": "nebula.dispatch",
              "GET /api/open-questions": "nebula.dispatch",
              "POST /api/open-questions": "nebula.dispatch",
              "GET /api/open-questions/:id": "nebula.dispatch",
              "PUT /api/open-questions/:id/answer": "nebula.dispatch",
              "GET /api/open-questions/:id/answers": "nebula.dispatch",
              "POST /api/open-questions/:id/answers": "nebula.dispatch",
              "GET /api/open-questions/:id/participants": "nebula.dispatch",
              "POST /api/open-questions/:id/participants": "nebula.dispatch",
              "PUT /api/open-questions/:id/resolve": "nebula.dispatch",
              "GET /api/open-questions/:id/timeline": "nebula.dispatch",
              "GET /api/plans": "nebula.dispatch",
              "POST /api/plans": "nebula.dispatch",
              "GET /api/plans/:id": "nebula.dispatch",
              "GET /api/plans/:planRef/candidates": "nebula.dispatch",
              "GET /api/preferences": "nebula.dispatch",
              "DELETE /api/preferences/:key": "nebula.dispatch",
              "PUT /api/preferences/:key": "nebula.dispatch",
              "POST /api/projection-overrides": "nebula.dispatch",
              "DELETE /api/projection-overrides/:id": "nebula.dispatch",
              "GET /api/projections": "nebula.dispatch",
              "POST /api/projections": "nebula.dispatch",
              "DELETE /api/projections/:id": "nebula.dispatch",
              "POST /api/projections/:id/render": "nebula.dispatch",
              "POST /api/refresh-stats": "nebula.dispatch",
              "GET /api/requirements": "nebula.dispatch",
              "POST /api/requirements": "nebula.dispatch",
              "DELETE /api/requirements/:id": "nebula.dispatch",
              "GET /api/requirements/:id": "nebula.dispatch",
              "PATCH /api/requirements/:id": "nebula.dispatch",
              "GET /api/requirements/:id/children": "nebula.dispatch",
              "POST /api/requirements/:id/compile": "nebula.dispatch",
              "GET /api/requirements/:id/dependencies": "nebula.dispatch",
              "POST /api/requirements/:id/dependencies": "nebula.dispatch",
              "DELETE /api/requirements/:id/dependencies/:depId": "nebula.dispatch",
              "POST /api/requirements/:id/move": "nebula.dispatch",
              "GET /api/requirements/:id/segment-sets": "nebula.dispatch",
              "PATCH /api/requirements/batch": "nebula.dispatch",
              "GET /api/role-leases": "nebula.dispatch",
              "POST /api/role-leases/:id/renew": "nebula.dispatch",
              "POST /api/role-leases/:id/revoke": "nebula.dispatch",
              "GET /api/role-leases/:role/status": "nebula.dispatch",
              "POST /api/role-leases/consume": "nebula.dispatch",
              "POST /api/role-leases/issue": "nebula.dispatch",
              "GET /api/role-leases/stale": "nebula.dispatch",
              "POST /api/role-leases/sweep": "nebula.dispatch",
              "GET /api/roles": "nebula.dispatch",
              "POST /api/roles": "nebula.dispatch",
              "DELETE /api/roles/:id": "nebula.dispatch",
              "GET /api/roles/:id": "nebula.dispatch",
              "PATCH /api/roles/:id": "nebula.dispatch",
              "GET /api/roles/drift": "nebula.dispatch",
              "GET /api/search": "nebula.dispatch",
              "POST /api/search/semantic": "nebula.dispatch",
              "POST /api/seed": "nebula.dispatch",
              "GET /api/segment-sets": "nebula.dispatch",
              "GET /api/segment-sets/:id": "nebula.dispatch",
              "POST /api/segments": "nebula.dispatch",
              "DELETE /api/segments/:id": "nebula.dispatch",
              "PATCH /api/segments/:id": "nebula.dispatch",
              "GET /api/sessions": "nebula.dispatch",
              "POST /api/sessions": "nebula.dispatch",
              "DELETE /api/sessions/:id": "nebula.dispatch",
              "PATCH /api/sessions/:id": "nebula.dispatch",
              "POST /api/snapshots": "nebula.dispatch",
              "GET /api/snapshots/:id/blocks": "nebula.dispatch",
              "GET /api/snapshots/:id/projection": "nebula.dispatch",
              "GET /api/snapshots/:id/references": "nebula.dispatch",
              "GET /api/specifications": "nebula.dispatch",
              "GET /api/specifications/:id": "nebula.dispatch",
              "POST /api/specifications/:id/link-requirements": "nebula.dispatch",
              "GET /api/specs": "nebula.dispatch",
              "GET /api/specs/:id": "nebula.dispatch",
              "POST /api/subsystems": "nebula.dispatch",
              "DELETE /api/subsystems/:id": "nebula.dispatch",
              "GET /api/subsystems/:id": "nebula.dispatch",
              "PATCH /api/subsystems/:id": "nebula.dispatch",
              "GET /api/subsystems/:id/agendas": "nebula.dispatch",
              "GET /api/subsystems/:id/docs": "nebula.dispatch",
              "GET /api/subsystems/:id/harvest-candidates": "nebula.dispatch",
              "GET /api/subsystems/:id/implementation-plans": "nebula.dispatch",
              "GET /api/subsystems/:id/specifications": "nebula.dispatch",
              "GET /api/subsystems/:id/work-requests": "nebula.dispatch",
              "POST /api/subsystems/move": "nebula.dispatch",
              "GET /api/systems": "nebula.dispatch",
              "POST /api/systems": "nebula.dispatch",
              "DELETE /api/systems/:id": "nebula.dispatch",
              "GET /api/systems/:id": "nebula.dispatch",
              "PATCH /api/systems/:id": "nebula.dispatch",
              "GET /api/systems/:id/agendas": "nebula.dispatch",
              "GET /api/systems/:id/docs": "nebula.dispatch",
              "GET /api/systems/:id/external-ids": "nebula.dispatch",
              "POST /api/systems/:id/external-ids": "nebula.dispatch",
              "DELETE /api/systems/:id/external-ids/:eid": "nebula.dispatch",
              "POST /api/systems/:id/folders": "nebula.dispatch",
              "GET /api/systems/:id/harvest-candidates": "nebula.dispatch",
              "GET /api/systems/:id/implementation-plans": "nebula.dispatch",
              "GET /api/systems/:id/info": "nebula.dispatch",
              "DELETE /api/systems/:id/info/:tabId": "nebula.dispatch",
              "PUT /api/systems/:id/info/:tabId": "nebula.dispatch",
              "GET /api/systems/:id/inventory": "nebula.dispatch",
              "GET /api/systems/:id/specifications": "nebula.dispatch",
              "GET /api/systems/:id/work-requests": "nebula.dispatch",
              "DELETE /api/systems/:systemId/folders/:folderId": "nebula.dispatch",
              "POST /api/systems/demote/:id": "nebula.dispatch",
              "GET /api/work-requests": "nebula.dispatch",
              "GET /api/work-requests/:id": "nebula.dispatch",
              "GET /api/workspaces": "nebula.dispatch",
              "POST /api/workspaces": "nebula.dispatch",
              "DELETE /api/workspaces/:id": "nebula.dispatch",
              "GET /health": "nebula.dispatch",
            },
          },
        ],
      },
    });
  }
}
