import { Router } from "express";
import {
  qAll,
  qRun,
  listProjections,
  getProjection,
  createProjection,
  updateProjection,
  deleteProjection,
  getPersonaForRole,
  getProceduresForRole,
} from "../db";
import { createHash } from "crypto";
import { writeFileSync, readFileSync, existsSync, mkdirSync, renameSync } from "fs";
import path from "path";

export const projectionsRouter = Router();

// ── Helpers ───────────────────────────────────────────────────────────

const GENERATED_HEADER = (name: string) =>
  `<!-- GENERATED by tackle-projector; source: projection:${name}; do not edit -->\n`;

/**
 * Deterministic {{var}} template substitution.
 * Replaces all {{varname}} tokens with values from the context object.
 */
function renderTemplate(template: string, ctx: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_match, name) => {
    return ctx[name] !== undefined ? ctx[name] : `{{${name}}}`;
  });
}

/**
 * Build context for a single projection row from source_query results + persona/procedures.
 */
async function buildContext(
  projection: any,
  queryRow: Record<string, any>
): Promise<Record<string, string>> {
  const ctx: Record<string, string> = {};

  // Merge query row values
  for (const [k, v] of Object.entries(queryRow)) {
    if (v !== null && v !== undefined) {
      ctx[k] = String(v);
    }
  }

  // Resolve persona if this projection needs it and has a role column
  const role = queryRow.role || queryRow.name;
  if (role && projection.template.includes("{{persona_body}}")) {
    const persona = await getPersonaForRole(role);
    ctx.persona_body = persona || `Activate as: ${role}.\n\nYou are the ${role}. Respond to user requests directly.`;
  }

  // Resolve procedures list if needed
  if (role && projection.template.includes("{{procedures_list}}")) {
    const procs = await getProceduresForRole(role);
    ctx.procedures_list = procs || "(no procedures available)";
  }

  return ctx;
}

/**
 * Compute SHA-256 of a string.
 */
function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

/**
 * Write a file with drift protection (.bak on overwrite).
 * Returns { written: boolean, sha: string, backedUp: boolean }
 */
function writeFileWithDrift(
  targetPath: string,
  content: string,
  lastSha256: string | null
): { written: boolean; sha: string; backedUp: boolean } {
  const newSha = sha256(content);
  const dir = path.dirname(targetPath);

  // Ensure directory exists
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  if (existsSync(targetPath)) {
    const existingContent = readFileSync(targetPath, "utf8");
    const existingSha = sha256(existingContent);

    // Idempotency: if unchanged, skip
    if (existingSha === newSha) {
      return { written: false, sha: newSha, backedUp: false };
    }

    // Drift protection: if known sha differs, create .bak
    if (lastSha256 && lastSha256 !== existingSha) {
      const ts = new Date().toISOString().replace(/[:.]/g, "-");
      const bakPath = `${targetPath}.bak-${ts}`;
      renameSync(targetPath, bakPath);
      writeFileSync(targetPath, content, "utf8");
      return { written: true, sha: newSha, backedUp: true };
    }

    // Untracked target: we have no stored sha, so we cannot prove the
    // existing file is ours. Never silently overwrite hand-authored
    // content — back it up first, then adopt.
    if (!lastSha256) {
      const ts = new Date().toISOString().replace(/[:.]/g, "-");
      const bakPath = `${targetPath}.bak-${ts}`;
      renameSync(targetPath, bakPath);
      writeFileSync(targetPath, content, "utf8");
      return { written: true, sha: newSha, backedUp: true };
    }

    // No drift (sha matches) — overwrite
    writeFileSync(targetPath, content, "utf8");
    return { written: true, sha: newSha, backedUp: false };
  }

  // New file
  writeFileSync(targetPath, content, "utf8");
  return { written: true, sha: newSha, backedUp: false };
}

// ── Routes ────────────────────────────────────────────────────────────

// GET /projections — list all projection configs
projectionsRouter.get("/", async (_req, res) => {
  try {
    const projections = await listProjections();
    res.json({ count: projections.length, projections });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// GET /projections/drift — compare on-disk sha vs last_sha256 for all enabled projections
projectionsRouter.get("/drift", async (_req, res) => {
  try {
    const projections = await listProjections();
    const driftReport: any[] = [];

    for (const p of projections) {
      if (!p.enabled || !p.target_path) continue;

      // For multi-role projections (opencode-agent), check all roles
      const rows = await resolveSourceQuery(p);
      for (const row of rows) {
        const targetPath = renderTemplate(p.target_path, row);
        const entry: any = {
          projection_id: p.id,
          name: p.name,
          target_path: targetPath,
          role: row.role || row.name || null,
        };

        if (existsSync(targetPath)) {
          const content = readFileSync(targetPath, "utf8");
          const diskSha = sha256(content);
          entry.disk_sha256 = diskSha;
          entry.stored_sha256 = p.last_sha256;
          // Untracked (never rendered) files with differing content are
          // drifted by definition — the old `diskSha !== (lastSha || diskSha)`
          // masked them as clean, hiding the first-render clobber hazard.
          entry.drift = p.last_sha256 ? diskSha !== p.last_sha256 : true;
          entry.untracked = !p.last_sha256;
        } else {
          entry.missing = true;
          entry.drift = true;
        }
        driftReport.push(entry);
      }
    }

    const drifted = driftReport.filter((d) => d.drift);
    res.json({
      total: driftReport.length,
      drifted: drifted.length,
      clean: driftReport.length - drifted.length,
      entries: driftReport,
    });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// GET /projections/:id — get single projection config
projectionsRouter.get("/:id", async (req, res) => {
  try {
    const p = await getProjection(req.params.id);
    if (!p) {
      res.status(404).json({ error: "Projection not found" });
      return;
    }
    res.json(p);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// POST /projections — create new projection config
projectionsRouter.post("/", async (req, res) => {
  try {
    const { name, description, type, source_query, template, parameter_schema, target_path, schedule, enabled } = req.body || {};
    if (!name || !template || !target_path) {
      res.status(400).json({ error: "name, template, and target_path are required" });
      return;
    }

    // Validate template placeholders against parameter_schema
    const placeholders = (template.match(/\{\{(\w+)\}\}/g) || []).map((m: string) => m.slice(2, -2));
    const schema = parameter_schema || {};
    const unknown = placeholders.filter((ph: string) => {
      // Allow well-known context vars that are always resolved
      const builtins = ["role", "role_description", "persona_body", "procedures_list", "name"];
      return !builtins.includes(ph) && !(ph in schema);
    });

    if (unknown.length > 0) {
      res.status(400).json({
        error: `Template contains placeholders not in parameter_schema: ${unknown.join(", ")}`,
        unknown_placeholders: unknown,
      });
      return;
    }

    const result = await createProjection({
      name,
      description: description || "",
      type: type || "deterministic",
      source_query: source_query || "",
      template,
      parameter_schema: schema,
      target_path,
      schedule: schedule || "",
      enabled: enabled !== undefined ? enabled : 1,
    });
    res.status(201).json({ created: true, ...result });
  } catch (e: any) {
    if (e.message?.includes("UNIQUE") || e.message?.includes("unique")) {
      res.status(409).json({ error: `Projection name '${req.body?.name}' already exists` });
      return;
    }
    res.status(500).json({ error: e.message });
  }
});

// PUT /projections/:id — update projection config
projectionsRouter.put("/:id", async (req, res) => {
  try {
    const existing = await getProjection(req.params.id);
    if (!existing) {
      res.status(404).json({ error: "Projection not found" });
      return;
    }

    const updates: Record<string, any> = {};
    for (const field of ["name", "description", "type", "source_query", "template", "parameter_schema", "target_path", "schedule", "enabled"]) {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
      }
    }

    if (Object.keys(updates).length === 0) {
      res.status(400).json({ error: "No fields to update" });
      return;
    }

    const result = await updateProjection(req.params.id, updates);
    res.json({ updated: true, ...result });
  } catch (e: any) {
    if (e.message?.includes("UNIQUE") || e.message?.includes("unique")) {
      res.status(409).json({ error: `Projection name '${req.body?.name}' already exists` });
      return;
    }
    res.status(500).json({ error: e.message });
  }
});

// DELETE /projections/:id — delete a projection config
projectionsRouter.delete("/:id", async (req, res) => {
  try {
    const existing = await getProjection(req.params.id);
    if (!existing) {
      res.status(404).json({ error: "Projection not found" });
      return;
    }
    const deleted = await deleteProjection(req.params.id);
    if (!deleted) {
      res.status(404).json({ error: "Projection not found" });
      return;
    }
    res.json({ deleted: true, id: req.params.id, name: existing.name });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// POST /projections/:id/render — render a single projection
projectionsRouter.post("/:id/render", async (req, res) => {
  try {
    const projection = await getProjection(req.params.id);
    if (!projection) {
      res.status(404).json({ error: "Projection not found" });
      return;
    }

    const results = await renderProjection(projection);
    res.json({ rendered: true, entries: results });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// POST /projections/render-all — render all enabled projections
projectionsRouter.post("/render-all", async (_req, res) => {
  try {
    const projections = await listProjections();
    const enabled = projections.filter((p: any) => p.enabled && p.template && p.target_path);

    const allResults: any[] = [];
    for (const projection of enabled) {
      const results = await renderProjection(projection);
      allResults.push(...results);
    }

    const written = allResults.filter((r: any) => r.written).length;
    const skipped = allResults.filter((r: any) => !r.written).length;
    const backedUp = allResults.filter((r: any) => r.backedUp).length;

    res.json({
      rendered: true,
      total: allResults.length,
      written,
      skipped,
      backedUp,
      entries: allResults,
    });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// ── Internal render logic ─────────────────────────────────────────────

/**
 * Resolve source_query for a projection.
 * Returns an array of row objects (at least one, even if source_query is empty).
 */
async function resolveSourceQuery(projection: any): Promise<Record<string, any>[]> {
  if (!projection.source_query) {
    return [{}];
  }
  try {
    // source_query can be a SQL query string
    const rows = await qAll(projection.source_query);
    if (rows.length === 0) {
      return [{}];
    }
    return rows;
  } catch (e: any) {
    // source_query failed — surface the error rather than silently producing bad output
    throw new Error(`source_query failed for projection '${projection.name}': ${e.message}`);
  }
}

/**
 * Resolve target path from a projection. If the target_path contains templates,
 * they are substituted from the row context.
 */
function resolveTargetPath(projection: any, row: Record<string, any>): string {
  let targetPath = projection.target_path;
  // Substitute row values into target_path (e.g., {{role}} → agent name)
  for (const [k, v] of Object.entries(row)) {
    if (v !== null && v !== undefined) {
      targetPath = targetPath.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), renderFilename(String(v)));
    }
  }
  // Any remaining {{var}} that doesn't match a row column stays literal
  return targetPath;
}

/**
 * Render a role/filename for use in paths (e.g., Big Pickle → BP, DBA → dba).
 */
function renderFilename(role: string): string {
  const mapping: Record<string, string> = {
    "big-pickle": "BP",
    "Big Pickle": "BP",
    "big_pickle": "BP",
    "dba": "dba",
    "DBA": "dba",
  };
  return mapping[role] || mapping[role.toLowerCase()] || role.toLowerCase().replace(/\s+/g, "-");
}

async function renderProjection(projection: any): Promise<any[]> {
  const rows = await resolveSourceQuery(projection);
  const results: any[] = [];

  for (const row of rows) {
    const ctx = await buildContext(projection, row);
    const renderedBody = renderTemplate(projection.template, ctx);
    const content = GENERATED_HEADER(projection.name) + renderedBody;
    const targetPath = resolveTargetPath(projection, row);

    // ── First-render clobber guard ────────────────────────────────────
    // If this projection has NEVER rendered (no stored sha) and the target
    // file already exists with different content, the file is almost
    // certainly hand-authored. Do not replace it — skip and report, so the
    // operator can reconcile the template with the real content first.
    // Without this, a freshly-registered stub template silently destroys
    // the live governance files on the next render-all (see the ACP
    // projection incident: 6 registered projections, zero renders,
    // startup-hook render-all would have replaced AGENTS.md/CLAUDE.md/etc
    // with ~300-char stubs, irreversibly).
    if (!projection.last_sha256 && existsSync(targetPath)) {
      const existing = readFileSync(targetPath, "utf8");
      if (sha256(existing) !== sha256(content)) {
        results.push({
          projection_id: projection.id,
          name: projection.name,
          target_path: targetPath,
          written: false,
          skipped: true,
          reason: "first-render clobber guard: existing file differs from template (hand-authored?)",
          role: row.role || row.name || null,
        });
        continue;
      }
    }

    const result = writeFileWithDrift(targetPath, content, projection.last_sha256);

    // Update last_rendered_at and last_sha256 in DB
    await qRun(
      `UPDATE tackle.projection_configs
       SET last_rendered_at = NOW(), last_sha256 = @sha, updated_at = NOW()
       WHERE id = @id`,
      { sha: result.sha, id: projection.id }
    );

    results.push({
      projection_id: projection.id,
      name: projection.name,
      target_path: targetPath,
      written: result.written,
      sha256: result.sha,
      backedUp: result.backedUp,
      role: row.role || row.name || null,
    });
  }

  return results;
}
