# Configuration to connect to broker gateway for service registration
broker.remote.gateway.url=http://localhost:8080

# Host server heartbeat registration
service.registry.url=http://localhost:8085
service.registry.registration.enabled=true
service.name=upload-service
service.host=localhost
service.framework=Spring Boot
service.version=1.0.0
service.operations=uploadFile,getUploadStatus,cancelUpload
heartbeat.interval.ms=30000
