// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

# Role Memory Procedure Registry: procedure cards and indexes, with a PG→Redis refresh endpoint.
# 
# Endpoint inventory generated from source route registrations by `nexus/tools/api-docs/`. Request/response bodies are generic; field-level contracts live in the service code and its README.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config =  {}, string serviceUrl = "http://localhost:3500") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function get health(map<string|string[]> headers = {}) returns JsonBody|error {
        string resourcePath = string `/health`;
        return self.clientEp->get(resourcePath, headers);
    }

    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function get procedure/[string slug](map<string|string[]> headers = {}) returns JsonBody|error {
        string resourcePath = string `/procedure/${getEncodedUri(slug)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function get procedures/[string role](map<string|string[]> headers = {}) returns JsonBody|error {
        string resourcePath = string `/procedures/${getEncodedUri(role)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Refresh (repopulate Redis from PG)
    #
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function post refresh(map<string|string[]> headers = {}) returns JsonBody|error {
        string resourcePath = string `/refresh`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }
}
