# Configuration to connect to broker gateway for service registration
broker.remote.gateway.url=http://localhost:8080

server.port=8084
spring.application.name=search-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/nexus_search
spring.data.mongodb.auto-index-creation=true

unsplash.api.key=YOUR_UNSPLASH_ACCESS_KEY_HERE
gemini.api.key=YOUR_GEMINI_API_KEY_HERE

# Logging
logging.level.com.aibizarchitecht.nexus.search=DEBUG
logging.level.org.springframework.web=DEBUG
