# Microprofile server properties
server.port=9093
server.host=0.0.0.0
# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics.rest-request.enabled=false
# Host server registration properties
service.registry.url=http://localhost:8085
service.name=user-access-service
service.host=localhost
registration.enabled=true
heartbeat.interval.seconds=30
# Database configuration
javax.sql.DataSource.user-access-ds.dataSourceClassName=com.mysql.cj.jdbc.MysqlDataSource
javax.sql.DataSource.user-access-ds.dataSource.url=jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true
javax.sql.DataSource.user-access-ds.dataSource.user=root
javax.sql.DataSource.user-access-ds.dataSource.password=rootpass
