// Drift sentinel — continuous contract-fidelity between committed specs
// and live services.
//
// For each configured target, loads the JSON snapshot of the service's
// committed openapi.yaml (generated by bin/ci-drift-snapshot.py) and
// probes EVERY parameterless GET endpoint the contract promises. Any
// endpoint missing (404), method-mismatched (405), or failing (5xx) on
// the live service is drift. This automates the runtime half of the
// contract-fidelity audit so it stops being a one-off.
//
// No live spec fetch exists (no TS service serves /openapi.json), and
// Ballerina has no YAML parser — the snapshot files are that bridge.
// Snapshots are committed; regenerate them via bin/ci-drift-snapshot.py
// whenever a spec changes, and the diff lands in review like any code.
//
// Resources live on the single gateway service in main.bal:
//   GET /gateway/driftCheck   — probe now, return full report
//   GET /gateway/driftStatus  — last cached report
//
// Quirk bank: 'service' is reserved even as a record field name (the
// row field is called svc); map-entry iteration needs `foreach var [k, v]`.

import ballerina/http;
import ballerina/io;

configurable map<string> driftTargets = ?;
configurable string snapshotDir = "./snapshots";

type DriftRow record {|
    string svc;
    string path;
    int status;
    boolean ok;
    string detail;
|};

type DriftReport record {|
    int checked;
    int drifted;
    DriftRow[] rows;
|};

DriftReport? lastReport = ();

function runDriftCheck() returns DriftReport {
    DriftRow[] rows = [];
    foreach var [name, base] in driftTargets.entries() {
        DriftRow[]|error svcRows = checkService(name, base);
        if svcRows is DriftRow[] {
            foreach var row in svcRows { rows.push(row); }
        } else {
            rows.push({
                svc: name,
                path: "(all)",
                status: -1,
                ok: false,
                detail: "probe setup failed: " + svcRows.message()
            });
        }
    }
    int drifted = rows.filter(r => !r.ok).length();
    DriftReport report = {
        checked: rows.length(),
        drifted: drifted,
        rows: rows
    };
    lock {
        lastReport = report;
    }
    return report;
}

function lastDriftReport() returns DriftReport? {
    lock {
        return lastReport;
    }
}

function reportToJson(DriftReport r) returns json =>
    {
        checked: r.checked,
        drifted: r.drifted,
        verdict: r.drifted == 0 ? "CLEAN" : "DRIFT",
        rows: r.rows
    };

// Probe every parameterless GET path in the snapshot against the live
// base URL. A connection failure marks the whole service as drifted —
// from where consumers stand, a down service IS contract drift.
function checkService(string name, string base) returns DriftRow[]|error {
    http:Client target = check new (base);
    json snap = check io:fileReadJson(snapshotDir + "/" + name + ".json");
    map<json> spec = check snap.ensureType();
    map<json> paths = check ((spec.get("paths") ?: {})).ensureType();

    DriftRow[] rows = [];
    foreach var [path, ops] in paths.entries() {
        if !(ops is map<json>) || !ops.hasKey("get") || path.includes("{") {
            continue;
        }
        int statusCode = -1;
        string detail = "";
        http:Response|http:ClientError res = target->get(path);
        if res is http:Response {
            statusCode = res.statusCode;
        } else {
            detail = res.message();
        }
        boolean ok = statusCode >= 200 && statusCode < 400;
        if !ok && detail == "" {
            detail = "contract promises GET " + path
                + "; live answered " + statusCode.toString();
        }
        rows.push({
            svc: name,
            path: path,
            status: statusCode,
            ok: ok,
            detail: detail
        });
    }
    return rows;
}
