/**
 * tackle-srv re-homing (Wave 3.5) — projections (ACP v1) domain.
 *
 * Ported from nexus/typescript/tackle-srv/src/routes/projections.ts.
 * Runs on the `tackle` named connection (search_path=tackle,public).
 * The projection rows are stored in tackle.projection_configs (qualified
 * explicitly, matching upstream's qAll against the tackle schema).
 */

import type { HttpContext } from '@adonisjs/core/http'
import { q } from '#services/nebula_helpers'
import { createHash } from 'node:crypto'
import { writeFileSync, readFileSync, existsSync, mkdirSync, renameSync } from 'node:fs'
import path from 'node:path'

const CONN = 'tackle'

const GENERATED_HEADER = (name: string) =>
  `<!-- GENERATED by tackle-projector; source: projection:${name}; do not edit -->\n`

function renderTemplate(template: string, ctx: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_match, name) => {
    return ctx[name] !== undefined ? ctx[name] : `{{${name}}}`
  })
}

function sha256(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

function writeFileWithDrift(
  targetPath: string,
  content: string,
  lastSha256: string | null
): { written: boolean; sha: string; backedUp: boolean } {
  const newSha = sha256(content)
  const dir = path.dirname(targetPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })

  if (existsSync(targetPath)) {
    const existingContent = readFileSync(targetPath, 'utf8')
    const existingSha = sha256(existingContent)
    if (existingSha === newSha) {
      return { written: false, sha: newSha, backedUp: false }
    }
    if (lastSha256 && lastSha256 !== existingSha) {
      const ts = new Date().toISOString().replace(/[:.]/g, '-')
      const bakPath = `${targetPath}.bak-${ts}`
      renameSync(targetPath, bakPath)
      writeFileSync(targetPath, content, 'utf8')
      return { written: true, sha: newSha, backedUp: true }
    }
    if (!lastSha256) {
      const ts = new Date().toISOString().replace(/[:.]/g, '-')
      const bakPath = `${targetPath}.bak-${ts}`
      renameSync(targetPath, bakPath)
      writeFileSync(targetPath, content, 'utf8')
      return { written: true, sha: newSha, backedUp: true }
    }
    writeFileSync(targetPath, content, 'utf8')
    return { written: true, sha: newSha, backedUp: false }
  }

  writeFileSync(targetPath, content, 'utf8')
  return { written: true, sha: newSha, backedUp: false }
}

function renderFilename(role: string): string {
  const mapping: Record<string, string> = {
    'big-pickle': 'BP',
    'Big Pickle': 'BP',
    big_pickle: 'BP',
    dba: 'dba',
    DBA: 'dba',
  }
  return mapping[role] || mapping[role.toLowerCase()] || role.toLowerCase().replace(/\s+/g, '-')
}

export default class TackleProjectionController {
  // GET /projections — list all projection configs
  async listProjections(_ctx: HttpContext) {
    const r = await q('SELECT * FROM tackle.projection_configs ORDER BY name', [], CONN)
    return { count: r.rows.length, projections: r.rows }
  }

  // GET /projections/drift — compare on-disk sha vs last_sha256
  async drift(_ctx: HttpContext) {
    const list = await q('SELECT * FROM tackle.projection_configs ORDER BY name', [], CONN)
    const driftReport: any[] = []

    for (const p of list.rows) {
      if (!p.enabled || !p.target_path) continue
      const rows = await this.resolveSourceQuery(p)
      for (const row of rows) {
        const targetPath = this.resolveTargetPath(p, row)
        const entry: any = {
          projection_id: p.id,
          name: p.name,
          target_path: targetPath,
          role: row.role || row.name || null,
        }
        if (existsSync(targetPath)) {
          const content = readFileSync(targetPath, 'utf8')
          const diskSha = sha256(content)
          entry.disk_sha256 = diskSha
          entry.stored_sha256 = p.last_sha256
          entry.drift = p.last_sha256 ? diskSha !== p.last_sha256 : true
          entry.untracked = !p.last_sha256
        } else {
          entry.missing = true
          entry.drift = true
        }
        driftReport.push(entry)
      }
    }

    const drifted = driftReport.filter((d) => d.drift)
    return {
      total: driftReport.length,
      drifted: drifted.length,
      clean: driftReport.length - drifted.length,
      entries: driftReport,
    }
  }

  // GET /projections/:id — single projection config
  async getProjection({ params, response }: HttpContext) {
    const r = await q('SELECT * FROM tackle.projection_configs WHERE id = $1', [params.id], CONN)
    if (r.rows.length === 0) return response.status(404).json({ error: 'Projection not found' })
    return response.json(r.rows[0])
  }

  // POST /projections — create new projection config
  async createProjection({ request, response }: HttpContext) {
    const { name, description, type, source_query, template, parameter_schema, target_path, schedule, enabled } = request.all()
    if (!name || !template || !target_path) {
      return response.status(400).json({ error: 'name, template, and target_path are required' })
    }
    const placeholders = (template.match(/\{\{(\w+)\}\}/g) || []).map((m: string) => m.slice(2, -2))
    const schema = parameter_schema || {}
    const builtins = ['role', 'role_description', 'persona_body', 'procedures_list', 'name']
    const unknown = placeholders.filter((ph: string) => !builtins.includes(ph) && !(ph in schema))
    if (unknown.length > 0) {
      return response.status(400).json({
        error: `Template contains placeholders not in parameter_schema: ${unknown.join(', ')}`,
        unknown_placeholders: unknown,
      })
    }
    try {
      const r = await q(
        `INSERT INTO tackle.projection_configs
         (name, description, type, source_query, template, parameter_schema, target_path, schedule, enabled)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
         RETURNING *`,
        [name, description || '', type || 'deterministic', source_query || '', template,
         JSON.stringify(schema), target_path, schedule || '', enabled !== undefined ? enabled : 1],
        CONN
      )
      return response.status(201).json({ created: true, ...r.rows[0] })
    } catch (e: any) {
      if (e.message?.includes('UNIQUE') || e.message?.includes('unique')) {
        return response.status(409).json({ error: `Projection name '${name}' already exists` })
      }
      return response.status(500).json({ error: e.message })
    }
  }

  // PUT /projections/:id — update projection config
  async updateProjection({ params, request, response }: HttpContext) {
    const existing = await q('SELECT * FROM tackle.projection_configs WHERE id = $1', [params.id], CONN)
    if (existing.rows.length === 0) return response.status(404).json({ error: 'Projection not found' })

    const body = request.all()
    const updates: Record<string, any> = {}
    for (const field of ['name', 'description', 'type', 'source_query', 'template', 'parameter_schema', 'target_path', 'schedule', 'enabled']) {
      if (body[field] !== undefined) updates[field] = body[field]
    }
    if (Object.keys(updates).length === 0) {
      return response.status(400).json({ error: 'No fields to update' })
    }

    const sets: string[] = []
    const vals: any[] = []
    let idx = 1
    for (const [k, v] of Object.entries(updates)) {
      sets.push(`${k} = $${idx++}`)
      vals.push(k === 'parameter_schema' && typeof v !== 'string' ? JSON.stringify(v) : v)
    }
    sets.push(`updated_at = NOW()`)
    vals.push(params.id)
    try {
      const r = await q(
        `UPDATE tackle.projection_configs SET ${sets.join(', ')} WHERE id = $${idx} RETURNING *`,
        vals,
        CONN
      )
      return response.json({ updated: true, ...r.rows[0] })
    } catch (e: any) {
      if (e.message?.includes('UNIQUE') || e.message?.includes('unique')) {
        return response.status(409).json({ error: `Projection name '${body.name}' already exists` })
      }
      return response.status(500).json({ error: e.message })
    }
  }

  // POST /projections/:id/render — render a single projection
  async renderProjectionRoute({ params, response }: HttpContext) {
    const r = await q('SELECT * FROM tackle.projection_configs WHERE id = $1', [params.id], CONN)
    if (r.rows.length === 0) return response.status(404).json({ error: 'Projection not found' })
    try {
      const results = await this.renderProjection(r.rows[0])
      return response.json({ rendered: true, entries: results })
    } catch (e: any) {
      return response.status(500).json({ error: e.message })
    }
  }

  // POST /projections/render-all — render all enabled projections
  async renderAll(_ctx: HttpContext) {
    const list = await q('SELECT * FROM tackle.projection_configs ORDER BY name', [], CONN)
    const enabled = list.rows.filter((p: any) => p.enabled && p.template && p.target_path)
    const allResults: any[] = []
    for (const projection of enabled) {
      const results = await this.renderProjection(projection)
      allResults.push(...results)
    }
    const written = allResults.filter((r: any) => r.written).length
    const skipped = allResults.filter((r: any) => !r.written).length
    const backedUp = allResults.filter((r: any) => r.backedUp).length
    return {
      rendered: true,
      total: allResults.length,
      written,
      skipped,
      backedUp,
      entries: allResults,
    }
  }

  // ── Internal render logic ─────────────────────────────────────
  private async resolveSourceQuery(projection: any): Promise<Record<string, any>[]> {
    if (!projection.source_query) return [{}]
    try {
      const rows = await q(projection.source_query, [], CONN)
      if (rows.rows.length === 0) return [{}]
      return rows.rows
    } catch (e: any) {
      throw new Error(`source_query failed for projection '${projection.name}': ${e.message}`)
    }
  }

  private resolveTargetPath(projection: any, row: Record<string, any>): string {
    let targetPath = projection.target_path
    for (const [k, v] of Object.entries(row)) {
      if (v !== null && v !== undefined) {
        targetPath = targetPath.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), renderFilename(String(v)))
      }
    }
    return targetPath
  }

  private async buildContext(projection: any, queryRow: Record<string, any>): Promise<Record<string, string>> {
    const ctx: Record<string, string> = {}
    for (const [k, v] of Object.entries(queryRow)) {
      if (v !== null && v !== undefined) ctx[k] = String(v)
    }
    const role = queryRow.role || queryRow.name
    if (role && projection.template.includes('{{persona_body}}')) {
      const r = await q(
        `SELECT body_md FROM prompts WHERE role = $1 AND slug = 'opencode-persona' ORDER BY version DESC LIMIT 1`,
        [role],
        CONN
      )
      ctx.persona_body = r.rows[0]?.body_md || `Activate as: ${role}.\n\nYou are the ${role}. Respond to user requests directly.`
    }
    if (role && projection.template.includes('{{procedures_list}}')) {
      const r = await q(
        `SELECT p.title FROM role_memory pm JOIN procedures p ON p.slug = pm.procedure_slug
         WHERE pm.role = $1 ORDER BY p.title`,
        [role],
        CONN
      )
      ctx.procedures_list = r.rows.map((x: any) => `- ${x.title}`).join('\n') || '(no procedures available)'
    }
    return ctx
  }

  private async renderProjection(projection: any): Promise<any[]> {
    const rows = await this.resolveSourceQuery(projection)
    const results: any[] = []
    for (const row of rows) {
      const ctx = await this.buildContext(projection, row)
      const renderedBody = renderTemplate(projection.template, ctx)
      const content = GENERATED_HEADER(projection.name) + renderedBody
      const targetPath = this.resolveTargetPath(projection, row)

      // First-render clobber guard (mirrors upstream)
      if (!projection.last_sha256 && existsSync(targetPath)) {
        const existing = readFileSync(targetPath, 'utf8')
        if (sha256(existing) !== sha256(content)) {
          results.push({
            projection_id: projection.id,
            name: projection.name,
            target_path: targetPath,
            written: false,
            skipped: true,
            reason: 'first-render clobber guard: existing file differs from template (hand-authored?)',
            role: row.role || row.name || null,
          })
          continue
        }
      }

      const result = writeFileWithDrift(targetPath, content, projection.last_sha256)
      await q(
        `UPDATE tackle.projection_configs
         SET last_rendered_at = NOW(), last_sha256 = $1, updated_at = NOW()
         WHERE id = $2`,
        [result.sha, projection.id],
        CONN
      )
      results.push({
        projection_id: projection.id,
        name: projection.name,
        target_path: targetPath,
        written: result.written,
        sha256: result.sha,
        backedUp: result.backedUp,
        role: row.role || row.name || null,
      })
    }
    return results
  }
}
