-- V8: Add domain-level system grouping (system_type, systems, system_services)
-- This enables grouping services into logical domains like "Harvest Pipeline"

-- System types (categories of systems)
CREATE TABLE registry.system_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    active_flag BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_system_type_name UNIQUE (name)
);

-- Systems (specific system instances)
CREATE TABLE registry.systems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    system_type_id BIGINT NOT NULL,
    description VARCHAR(1000),
    active_flag BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_systems_name UNIQUE (name),
    CONSTRAINT fk_systems_type FOREIGN KEY (system_type_id) REFERENCES registry.system_type(id)
);

-- Junction table: which services belong to which systems
CREATE TABLE registry.system_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    role_in_system VARCHAR(100), -- e.g., 'orchestrator', 'worker', 'store', 'bridge'
    active_flag BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_system_services_system FOREIGN KEY (system_id) REFERENCES registry.systems(id),
    CONSTRAINT fk_system_services_service FOREIGN KEY (service_id) REFERENCES registry.services(id),
    CONSTRAINT uk_system_service UNIQUE (system_id, service_id)
);

-- Seed system types
INSERT INTO registry.system_type (name, description) VALUES
    ('Ingest Pipeline', 'Systems that collect, transform, and load data from external sources'),
    ('LLM Orchestration', 'Systems that manage AI/ML model inference, prompts, and agent workflows'),
    ('Knowledge Management', 'Systems that store, index, and retrieve structured knowledge'),
    ('Execution Pipeline', 'Systems that coordinate task execution, scheduling, and state management');

-- Seed systems
INSERT INTO registry.systems (name, system_type_id, description) VALUES
    ('Harvest Pipeline', (SELECT id FROM registry.system_type WHERE name = 'Ingest Pipeline'),
     'Data collection pipeline: rover scripts → nebula-srv → cascade events'),
    ('Agent Management', (SELECT id FROM registry.system_type WHERE name = 'LLM Orchestration'),
     'Agent lifecycle, roles, clock-in/out, and Assembly messaging'),
    ('Knowledge Graph', (SELECT id FROM registry.system_type WHERE name = 'Knowledge Management'),
     'Nebula schema: requirements, specs, cross-references, and projections'),
    ('WorkRequest Pipeline', (SELECT id FROM registry.system_type WHERE name = 'Execution Pipeline'),
     'Task orchestration: conduit-mcp → kernel → execution');

-- Link existing services to systems
-- Harvest Pipeline
INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'orchestrator'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Harvest Pipeline' AND svc.name = 'rover'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'store'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Harvest Pipeline' AND svc.name = 'nebula-srv'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'bridge'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Harvest Pipeline' AND svc.name = 'cascade-srv'
ON CONFLICT (system_id, service_id) DO NOTHING;

-- Agent Management
INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'orchestrator'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Agent Management' AND svc.name = 'peb-kernel'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'messaging'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Agent Management' AND svc.name = 'assembly-mcp'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'memory'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Agent Management' AND svc.name = 'role-memory-srv'
ON CONFLICT (system_id, service_id) DO NOTHING;

-- Knowledge Graph
INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'store'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Knowledge Graph' AND svc.name = 'nebula-srv'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'mcp'
FROM registry.systems s, registry.services svc
WHERE s.name = 'Knowledge Graph' AND svc.name = 'nebula-mcp'
ON CONFLICT (system_id, service_id) DO NOTHING;

-- WorkRequest Pipeline
INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'orchestrator'
FROM registry.systems s, registry.services svc
WHERE s.name = 'WorkRequest Pipeline' AND svc.name = 'conduit-mcp'
ON CONFLICT (system_id, service_id) DO NOTHING;

INSERT INTO registry.system_services (system_id, service_id, role_in_system)
SELECT s.id, svc.id, 'executor'
FROM registry.systems s, registry.services svc
WHERE s.name = 'WorkRequest Pipeline' AND svc.name = 'peb-kernel'
ON CONFLICT (system_id, service_id) DO NOTHING;

-- Create indexes for common queries
CREATE INDEX idx_system_services_system ON registry.system_services(system_id);
CREATE INDEX idx_system_services_service ON registry.system_services(service_id);
CREATE INDEX idx_systems_type ON registry.systems(system_type_id);
