#!/usr/bin/env python3
"""E2E: V201 — bcrypt write-guard (V191 re-apply + self-hashing triggers) on
a throwaway DB, wr-conf house pattern (V191/V190 companions).

The skeleton recreates the PRE-V191 live shape (census 2026-09-20, titanium:
assembly.users 8 plaintext rows, gateway.users 2). Then the REAL
sql/V201__bcrypt_write_guard.sql applies and the contract is exercised
against live constraint + trigger behavior — no mocks on the DB path:

  - V191 backfill rides inside V201: every plaintext password becomes bcrypt
    ($2…, 60 chars) and the ORIGINAL credentials still round-trip through
    pgcrypto crypt() (what BCryptPasswordEncoder.matches() implements)
  - the V191 born-clean CHECKs are present after V201
  - trigger self-hash: a plaintext INSERT is normalized to a valid bcrypt
    hash (the known writers — assembly-srv createUser, adonis changeme
    default — keep functioning); a plaintext UPDATE re-hash likewise
  - CHECK backstop: with the trigger dropped, raw plaintext is REJECTED by
    the database itself (guard-removal can never reopen the plaintext class)
  - no laundering: a '$2'-prefixed non-hash passes the trigger untouched and
    is still rejected by the CHECK (length = 60) — garbage stays loud
  - empty string escape still allowed; pre-existing hashes never re-hashed
  - idempotent re-apply: second V201 run is a no-op (hashes unchanged)
"""
import os
import unittest
import uuid

import psycopg2

_REPO_ROOT = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", ".."))
V201_PATH = os.path.join(_REPO_ROOT, "sql", "V201__bcrypt_write_guard.sql")

DSN = os.environ.get("CONDUIT_PG_DSN",
                     "postgresql://pguser:pgpass@localhost:5432/postgres")

SKELETON_SQL = """
CREATE SCHEMA assembly;
CREATE SCHEMA gateway;

CREATE TABLE assembly.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    identifier varchar(255) NOT NULL DEFAULT '',
    admin boolean NOT NULL DEFAULT false,
    alias varchar(100) NOT NULL UNIQUE,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    avatar_url varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- gateway.users live shape: bigint PK, no default observed
CREATE TABLE gateway.users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin boolean NOT NULL DEFAULT false,
    alias varchar(255) NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT now(),
    email varchar(255),
    identifier varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now()
);

INSERT INTO assembly.users (alias, email, identifier, password, admin) VALUES
    ('admin',    'admin@localhost',    'admin',  'admin',      true),
    ('copilot',  'copilot@localhost',  'x',      'x',          false),
    ('claude',   'claude@localhost',   'x',      'x',          false),
    ('gemini',   'gemini@localhost',   'x',      'x',          false),
    ('chatgpt',  'chatgpt@localhost',  'x',      'x',          false),
    ('Rover',    'rover@localhost',    'roverpw', 'roverpw',   false),
    ('inspector','inspector@localhost','agent',  'agent',      false),
    ('critic',   'critic@localhost',   'agent',  'agent',      false);

INSERT INTO gateway.users (alias, email, identifier, password) VALUES
    ('admin',    'admin@localhost',    'admin',  'admin'),
    ('testuser', 'test@localhost',     'secret123', 'secret123');
"""


class ThrowawayDB:
    def __init__(self, dbname_prefix):
        self.dbname = f"nexus_v201_{dbname_prefix}_{os.getpid()}_{uuid.uuid4().hex[:6]}"
        self.conn = None

    def __enter__(self):
        admin = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/postgres")
        admin.autocommit = True
        with admin.cursor() as cur:
            cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}"')
            cur.execute(f'CREATE DATABASE "{self.dbname}"')
        admin.close()
        self.conn = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/" + self.dbname)
        self.conn.autocommit = True
        with self.conn.cursor() as cur:
            cur.execute(SKELETON_SQL)
        return self

    def __exit__(self, *exc):
        try:
            if self.conn:
                self.conn.close()
        finally:
            admin = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/postgres")
            admin.autocommit = True
            with admin.cursor() as cur:
                cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}"')
            admin.close()

    def sql(self, stmt, params=None):
        with self.conn.cursor() as cur:
            cur.execute(stmt, params)
            rows = cur.fetchall() if cur.description else None
        if rows and len(rows) == 1 and len(rows[0]) == 1:
            return rows[0][0]
        return rows

    def expect_error(self, stmt, params=None, fragment=None):
        try:
            self.sql(stmt, params)
        except psycopg2.Error as exc:
            # autocommit: clear the aborted implicit transaction server-side
            self.conn.cursor().execute("ROLLBACK")
            msg = str(exc).split("\n")[0]
            if fragment and fragment not in msg:
                raise AssertionError(
                    f"expected error containing {fragment!r}, got: {msg}")
            return msg
        raise AssertionError("expected the statement to fail")

    def apply_v201(self):
        with open(V201_PATH) as fh:
            self.sql(fh.read())


class BackfillViaV201(unittest.TestCase):
    def test_01_v191_rides_inside_v201(self):
        db = ThrowawayDB("backfill")
        with db as d:
            d.apply_v201()
            for surf in ("assembly.users", "gateway.users"):
                bad = d.sql(
                    f"SELECT count(*) FILTER (WHERE password NOT LIKE '$2%' "
                    f"OR length(password) <> 60) FROM {surf}")
                total = d.sql(f"SELECT count(*) FROM {surf}")
                self.assertEqual(bad, 0, f"{surf}: non-bcrypt rows remain")
                self.assertGreater(total, 0, f"{surf}: skeleton rows missing")
            # Original credentials round-trip through bcrypt.
            self.assertEqual(d.sql(
                "SELECT crypt('admin', password) = password FROM assembly.users "
                "WHERE alias='admin'"), True)
            self.assertEqual(d.sql(
                "SELECT crypt('secret123', password) = password FROM gateway.users "
                "WHERE alias='testuser'"), True)
            # V191 CHECKs are present.
            for surf in ("assembly.users", "gateway.users"):
                self.assertEqual(d.sql(
                    "SELECT count(*) FROM pg_constraint "
                    "WHERE conname='users_password_bcrypt_check' "
                    f"AND conrelid='{surf}'::regclass"), 1)


class TriggerGuard(unittest.TestCase):
    def test_02_plaintext_insert_self_hashes(self):
        db = ThrowawayDB("ins-selfhash")
        with db as d:
            d.apply_v201()
            # The assembly-srv createUser pattern: INSERT with raw plaintext.
            d.sql(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('writer1', 'w1@localhost', 'pw', 'plaintextpw')")
            pw = d.sql("SELECT password FROM assembly.users WHERE alias='writer1'")
            self.assertTrue(pw.startswith("$2"), f"trigger did not hash: {pw}")
            self.assertEqual(len(pw), 60, f"hash malformed: {pw}")
            # And the original plaintext still round-trips.
            self.assertEqual(d.sql(
                "SELECT crypt('plaintextpw', password) = password "
                "FROM assembly.users WHERE alias='writer1'"), True)
            # gateway surface equally guarded (update path).
            d.sql("UPDATE gateway.users SET password='newsecret' WHERE alias='admin'")
            pw = d.sql("SELECT password FROM gateway.users WHERE alias='admin'")
            self.assertTrue(pw.startswith("$2") and len(pw) == 60,
                            f"trigger did not hash on UPDATE: {pw}")

    def test_03_check_backstop_without_trigger(self):
        db = ThrowawayDB("backstop")
        with db as d:
            d.apply_v201()
            d.sql("DROP TRIGGER trg_bcrypt_write_guard ON assembly.users")
            # With the guard removed, the CHECK still rejects plaintext —
            # guard removal can never reopen the plaintext class.
            d.expect_error(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('sneaky', 'sneaky@localhost', 'pw', 'plaintextpw')",
                fragment="users_password_bcrypt_check")
            d.expect_error(
                "UPDATE assembly.users SET password = 'admin' WHERE alias='admin'",
                fragment="users_password_bcrypt_check")
            # Valid hashes and '' still accepted.
            d.sql(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('hashed', 'h@localhost', 'x', "
                "crypt('realpw', gen_salt('bf', 10)))")
            d.sql(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('empty', 'e@localhost', '', '')")

    def test_04_no_laundering_of_garbage(self):
        db = ThrowawayDB("garbage")
        with db as d:
            d.apply_v201()
            # '$2'-prefixed non-hash: trigger passes it through untouched,
            # CHECK (length=60) rejects it loudly.
            d.expect_error(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('garb', 'g@localhost', 'pw', '$2short')",
                fragment="users_password_bcrypt_check")

    def test_05_preexisting_hash_never_rehashed_and_idempotent(self):
        db = ThrowawayDB("preserve")
        with db as d:
            d.sql("""
                INSERT INTO assembly.users (alias, email, identifier, password)
                VALUES ('already', 'already@localhost', 'pw',
                        '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjPeGqBQVLfJ9X0nYbRJRBQ8RfV9Aa')
            """)
            pre = d.sql("SELECT password FROM assembly.users WHERE alias='already'")
            d.apply_v201()
            post = d.sql("SELECT password FROM assembly.users WHERE alias='already'")
            self.assertEqual(pre, post, "existing hash was re-hashed")
            # Second V201 apply: zero-row no-op, hashes byte-identical.
            h1 = d.sql(
                "SELECT md5(string_agg(password, '' ORDER BY alias)) FROM assembly.users")
            d.apply_v201()
            h2 = d.sql(
                "SELECT md5(string_agg(password, '' ORDER BY alias)) FROM assembly.users")
            self.assertEqual(h1, h2, "re-apply changed hashes")
            # Triggers survive the re-apply (DROP IF EXISTS + CREATE).
            self.assertEqual(d.sql(
                "SELECT count(*) FROM pg_trigger "
                "WHERE tgrelid='assembly.users'::regclass "
                "AND tgname='trg_bcrypt_write_guard' AND NOT tgisinternal"), 1)
            self.assertEqual(d.sql(
                "SELECT count(*) FROM pg_trigger "
                "WHERE tgrelid='gateway.users'::regclass "
                "AND tgname='trg_bcrypt_write_guard' AND NOT tgisinternal"), 1)


if __name__ == "__main__":
    unittest.main()
