"""
wr-conf-014: canonical WR landing pre-stage (V163) conformance suite.

Executable regression for the V163 pre-stage migration (PR #251), implementing
the analyst review corrections (record 51462bfd — request changes):

  C1  execution_linkage key alignment: the trigger must accept the artifact's
      keys (lease_ref / attempt_refs / receipt_refs) and refuse the old
      trigger-only keys (lease / attempt / receipt).
  C2  hatch-first: vision.allow_ungated_wr_landing must be honored BEFORE any
      refusal — a hatched canonical write passes even pre-ratification, and a
      hatched legacy write always passes (session-LOCAL, gone afterward).
  C3  shape_version enforcement: canonical landing requires an explicit
      shape_version equal to the active ratified shape (P1023 otherwise).
  C4  business_key uniqueness: UNIQUE partial index — duplicate non-null
      business keys refuse; multiple NULL (legacy) keys coexist.
  C5  full v0.1 conformance per schemas/work-request/canonical-shape.v0.1.json:
      required fields, JSON types, object/array shapes, enum domains.

HERMETIC: each run creates a throwaway database (nexus_v163_test_<pid>), builds
a faithful skeleton of the touched surfaces (vision.work_requests 13-column
baseline, semantics.canonical_asset FK target, conduit runtime tables), applies
the real sql/V163__wr_canonical_landing_prestage.sql, runs the scenarios, and
DROPs the database. The live nexus database is never touched.

Usage:
    CONDUIT_PG_DSN=postgresql://pguser:pgpass@localhost:5432/postgres \
      python3 -m pytest python/nexus_core/wrp/tests/test_conformance_wr_landing_prestage.py -v
"""

import json
import os
import sys
import unittest

_SELF_DIR = os.path.dirname(os.path.abspath(__file__))
# 4 ups: tests -> wrp -> nexus_core -> python -> repo root
_REPO_ROOT = os.path.abspath(os.path.join(_SELF_DIR, "..", "..", "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

DSN = os.environ.get("CONDUIT_PG_DSN", "postgresql://pguser:pgpass@localhost:5432/postgres")

# Path to the migration under test, resolved from this test's repo location.
V163_PATH = os.path.join(_REPO_ROOT, "sql", "V163__wr_canonical_landing_prestage.sql")


def _admin_connect(dbname):
    import psycopg2
    # Connect to the maintenance database to create/drop throwaway DBs.
    dsn = DSN.rsplit("/", 1)[0] + "/" + dbname
    return psycopg2.connect(dsn)


def _exec(cur, sql):
    cur.execute(sql)


class _HermeticDB:
    """Throwaway per-run database with the V163 pre-stage applied."""

    def __init__(self):
        self.dbname = f"nexus_v163_test_{os.getpid()}"

    def __enter__(self):
        conn = _admin_connect("postgres")
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}"')
            cur.execute(f'CREATE DATABASE "{self.dbname}"')
        conn.close()
        self.conn = _admin_connect(self.dbname)
        self.conn.autocommit = True
        self._build_skeleton()
        self._apply_v163()
        return self

    def __exit__(self, *exc):
        try:
            self.conn.close()
        finally:
            conn = _admin_connect("postgres")
            conn.autocommit = True
            with conn.cursor() as cur:
                cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}" WITH (FORCE)')
            conn.close()

    def _build_skeleton(self):
        """Faithful baseline of the touched surfaces (V163 §7 evidence)."""
        with self.conn.cursor() as cur:
            for schema in ("vision", "semantics", "conduit"):
                cur.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
            # semantics.canonical_asset — FK target for work_requests.asset_id
            cur.execute("""
                CREATE TABLE semantics.canonical_asset (
                    asset_id uuid PRIMARY KEY DEFAULT gen_random_uuid()
                )
            """)
            # vision.work_requests — 13-column pre-V163 baseline (verified live)
            cur.execute("""
                CREATE TABLE vision.work_requests (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    wr_id text,
                    dco_json text,
                    context jsonb,
                    status text,
                    step_outputs text,
                    recorded_on_dt timestamptz NOT NULL DEFAULT now(),
                    recorded_until_dt timestamptz NOT NULL DEFAULT 'infinity'::timestamptz,
                    work_request_uuid text,
                    title text,
                    nexus_work_request_id uuid,
                    asset_id uuid REFERENCES semantics.canonical_asset(asset_id),
                    entity_key text
                )
            """)
            # Two legacy rows (as live: business_key will be NULL after §2).
            cur.execute("""
                INSERT INTO vision.work_requests (wr_id, status)
                VALUES ('legacy-1', 'archived'), ('legacy-2', 'archived')
            """)
            # conduit WR runtime tables (never-drop pins reference them)
            cur.execute("""
                CREATE TABLE conduit.work_request_events (
                    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    work_request_id uuid,
                    event_type text,
                    payload jsonb,
                    created_at timestamptz NOT NULL DEFAULT now()
                )
            """)
            cur.execute("""
                CREATE TABLE conduit.work_request_state (
                    work_request_id uuid PRIMARY KEY,
                    state text,
                    updated_at timestamptz NOT NULL DEFAULT now()
                )
            """)

    def _apply_v163(self):
        with self.conn.cursor() as cur:
            with open(V163_PATH, "r", encoding="utf-8") as fh:
                sql = fh.read()
            # Strip the trailing §7 comment block safely: psql runs the whole
            # file fine (comments are legal SQL), so no stripping is needed.
            cur.execute(sql)


class TestWRLandingPrestage(unittest.TestCase):
    """V163 conformance — C1..C5 + hatch + never-drop guard."""

    @classmethod
    def setUpClass(cls):
        cls.herm = _HermeticDB().__enter__()
        cls.conn = cls.herm.conn

    @classmethod
    def tearDownClass(cls):
        cls.herm.__exit__()

    # ---- helpers ----------------------------------------------------------

    def _sql(self, query, params=None):
        """Run a statement on a FRESH connection; return rows.

        Fresh connection per statement: a refused statement aborts its
        transaction, and we don't want that poisoning the next case.
        """
        import psycopg2
        conn = _admin_connect(self.herm.dbname)
        try:
            cur = conn.cursor()
            cur.execute(query, params)
            rows = cur.fetchall() if cur.description else []
            conn.commit()
            return rows
        except psycopg2.Error:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _refused(self, query, expect_fragment=None):
        """Assert the statement raises, and (optionally) the message fragment."""
        import psycopg2
        try:
            self._sql(query)
        except psycopg2.Error as e:
            msg = (e.diag.message_primary or "") if e.diag else str(e)
            if expect_fragment:
                self.assertIn(expect_fragment, msg)
            return msg
        self.fail(f"expected refusal, statement succeeded: {query[:120]}")

    def _set_hatch(self, on):
        # NOTE: the hatch is session-LOCAL — this helper is only meaningful on
        # the same connection that later runs the hatched statement. Use
        # _sql_hatched for that; this helper exists for explicit "hatch off"
        # assertions only.
        self._sql(f"SET vision.allow_ungated_wr_landing = {'on' if on else 'off'}")

    def _sql_hatched(self, query, setting='vision.allow_ungated_wr_landing', value='on'):
        """Run SET <setting>=<value> + query on ONE connection.

        The hatch is session-LOCAL by design (the security property under
        test): a SET on connection A never leaks to connection B. Hatched
        scenarios must therefore issue the SET and the statement on the same
        connection, then close it — after which the hatch is verifiably gone.
        """
        import psycopg2
        conn = _admin_connect(self.herm.dbname)
        try:
            cur = conn.cursor()
            cur.execute(f"SET {setting} = '{value}'")
            cur.execute(query)
            rows = cur.fetchall() if cur.description else []
            conn.commit()
            return rows
        except psycopg2.Error:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _ratify_shape(self, version="v0.1"):
        self._sql(f"""
            INSERT INTO vision.work_request_shape_registry
                (shape_version, artifact_path, artifact_sha256, ratification_state)
            VALUES ('{version}', 'schemas/work-request/canonical-shape.{version}.json',
                    '{'a' * 64}', 'ratified')
        """)

    def _unratify_shape(self, version="v0.1"):
        # DELETE (not UPDATE-to-superseded): shape_version is the PRIMARY KEY,
        # so a superseded row would collide with the next test's re-ratify.
        # The guard ignores DELETEs (tombstones are contract-legal), so this
        # is the clean per-test teardown.
        self._sql(f"DELETE FROM vision.work_request_shape_registry WHERE shape_version = '{version}'")

    def _canonical_row(self, **overrides):
        """A fully conforming v0.1 canonical payload (per the artifact)."""
        row = {
            "wr_id": "wr-canonical-1",
            "status": "open",
            "business_key": "bk-1",
            "relation_payload": json.dumps({"source": "rover", "ref": "x1"}),
            "intent_payload": json.dumps({
                "problem_statement": "something is broken",
                "desired_outcome": "it works again",
                "priority": "high",
            }),
            "lineage": json.dumps({"plan": "plan-0003"}),
            "decomposition": json.dumps({"steps": [{"n": 1, "do": "a"}]}),
            "execution_linkage": json.dumps({
                "lease_ref": "lease-1",
                "attempt_refs": ["att-1"],
                "receipt_refs": ["rec-1"],
            }),
            "evidence_obligations": json.dumps([{"kind": "log"}]),
            "inquiry": json.dumps({
                "read_set_scope": {"tables": ["nebula.agent_records"]},
                "evaluator_ref": "eval-1",
                "expected_outcome_type": "report",
                "evidence_requirements": ["ev-1"],
            }),
            "shape_version": "v0.1",
        }
        row.update(overrides)
        cols = ", ".join(row.keys())
        vals = []
        for v in row.values():
            if v is None:
                vals.append("NULL")
            elif isinstance(v, bool) or isinstance(v, int):
                vals.append(str(v))
            else:
                vals.append("'" + str(v).replace("'", "''") + "'")
        return f"INSERT INTO vision.work_requests ({cols}) VALUES ({', '.join(vals)})"

    # ---- 1. apply + postconditions -----------------------------------------

    def test_ac1_apply_postconditions(self):
        rows = self._sql("""
            SELECT column_name FROM information_schema.columns
            WHERE table_schema='vision' AND table_name='work_requests'
              AND column_name IN ('business_key','relation_payload','intent_payload',
                                  'lineage','decomposition','execution_linkage',
                                  'evidence_obligations','inquiry','shape_version')
        """)
        self.assertEqual(len(rows), 9)
        idx = self._sql("""
            SELECT indexdef FROM pg_indexes
            WHERE schemaname='vision' AND tablename='work_requests'
              AND indexname='uq_vision_work_requests_business_key'
        """)
        self.assertEqual(len(idx), 1)
        self.assertIn("UNIQUE", idx[0][0])
        reg = self._sql("SELECT count(*) FROM vision.work_request_shape_registry")
        self.assertEqual(reg[0][0], 0, "registry must ship EMPTY (no seeding)")

    # ---- 2. legacy admission + C2 hatch-first -------------------------------

    def test_ac2_legacy_write_passes_pre_ratification_no_hatch(self):
        # C2 correction of the old strict-gate: legacy-shaped writes are not
        # stranded pre-ratification (no P1021 for legacy rows).
        self._sql("""
            INSERT INTO vision.work_requests (wr_id, status) VALUES ('legacy-3', 'open')
        """)
        rows = self._sql("SELECT count(*) FROM vision.work_requests WHERE wr_id='legacy-3'")
        self.assertEqual(rows[0][0], 1)

    def test_ac3_hatched_legacy_write_passes_and_hatch_is_session_local(self):
        self._sql_hatched(
            "INSERT INTO vision.work_requests (wr_id, status) VALUES ('legacy-4', 'open')")
        rows = self._sql("SELECT count(*) FROM vision.work_requests WHERE wr_id='legacy-4'")
        self.assertEqual(rows[0][0], 1)
        # hatch must be gone on a fresh connection (session-LOCAL)
        self._refused(self._canonical_row(wr_id="wr-hatch-leak", business_key="bk-leak"),
                      "P1021")

    # ---- 3. canonical gate pre/post ratification ----------------------------

    def test_ac4_canonical_write_pre_ratification_refused_p1021(self):
        self._refused(self._canonical_row(business_key="bk-prerat"),
                      "P1021: no ratified canonical WorkRequest shape")

    def test_ac5_hatch_first_admits_canonical_write_pre_ratification(self):
        # C2: the hatch is evaluated BEFORE the P1021 refusal — the same
        # canonical write that is refused unhatched (AC4) passes hatched,
        # even with NO ratified shape registered.
        self._sql_hatched(self._canonical_row(
            wr_id="wr-hatched-pre", business_key="bk-hatched"))
        rows = self._sql("SELECT count(*) FROM vision.work_requests WHERE wr_id='wr-hatched-pre'")
        self.assertEqual(rows[0][0], 1)

    def test_ac6_conforming_canonical_write_admitted_and_stamp_required(self):
        self._ratify_shape("v0.1")
        try:
            self._sql(self._canonical_row(wr_id="wr-ok-1", business_key="bk-ok-1"))
            rows = self._sql("""
                SELECT shape_version, intent_payload->>'priority'
                FROM vision.work_requests WHERE wr_id='wr-ok-1'
            """)
            self.assertEqual(rows[0][0], "v0.1")
            self.assertEqual(rows[0][1], "high")
        finally:
            self._unratify_shape("v0.1")

    # ---- 4. C1 execution_linkage keys ---------------------------------------

    def test_ac7_linkage_artifact_keys_accepted(self):
        self._ratify_shape("v0.1")
        try:
            self._sql(self._canonical_row(
                wr_id="wr-c1-ok", business_key="bk-c1-ok",
                execution_linkage=json.dumps({
                    "lease_ref": "lease-9",
                    "attempt_refs": ["att-1", "att-2"],
                    "receipt_refs": [],
                })))
            rows = self._sql(
                "SELECT execution_linkage->>'lease_ref' FROM vision.work_requests WHERE wr_id='wr-c1-ok'")
            self.assertEqual(rows[0][0], "lease-9")
        finally:
            self._unratify_shape("v0.1")

    def test_ac8_linkage_old_trigger_keys_refused(self):
        self._ratify_shape("v0.1")
        try:
            self._refused(self._canonical_row(
                business_key="bk-c1-bad",
                execution_linkage=json.dumps({"lease": "lease-1"})),
                "refs-only")
            self._refused(self._canonical_row(
                business_key="bk-c1-bad2",
                execution_linkage=json.dumps({"attempt": [], "receipt": []})),
                "refs-only")
        finally:
            self._unratify_shape("v0.1")

    def test_ac9_linkage_embedded_state_refused(self):
        self._ratify_shape("v0.1")
        try:
            self._refused(self._canonical_row(
                business_key="bk-c1-embed",
                execution_linkage=json.dumps({
                    "lease_ref": "l1",
                    "attempt_refs": [{"id": "att-1", "status": "running"}]})),
                "string refs")
        finally:
            self._unratify_shape("v0.1")

    # ---- 5. C3 shape_version enforcement ------------------------------------

    def test_ac10_shape_version_mismatch_refused_p1023(self):
        self._ratify_shape("v0.1")
        try:
            self._refused(self._canonical_row(
                business_key="bk-c3-a", shape_version="v0.9"), "P1023")
            self._refused(self._canonical_row(
                business_key="bk-c3-b", shape_version=None), "P1023")
        finally:
            self._unratify_shape("v0.1")

    # ---- 6. C4 business_key uniqueness --------------------------------------

    def test_ac11_duplicate_business_key_refused_nulls_coexist(self):
        self._ratify_shape("v0.1")
        try:
            self._sql(self._canonical_row(wr_id="wr-u1", business_key="bk-dup"))
            import psycopg2
            try:
                self._sql(self._canonical_row(wr_id="wr-u2", business_key="bk-dup"))
                self.fail("duplicate business_key must violate the unique index")
            except psycopg2.Error as e:
                self.assertIn("uq_vision_work_requests_business_key", str(e))
        finally:
            self._unratify_shape("v0.1")
        # NULL (legacy) keys never collide: add another hatched legacy row.
        # (Self-contained: counts only skeleton rows + this test's row — test
        # methods run alphabetically, so cross-test row assumptions are unsafe.)
        self._sql_hatched(
            "INSERT INTO vision.work_requests (wr_id, status) VALUES ('legacy-5','open')")
        rows = self._sql("""
            SELECT count(*) FROM vision.work_requests
            WHERE wr_id IN ('legacy-1','legacy-2','legacy-5')
              AND business_key IS NULL
        """)
        self.assertEqual(rows[0][0], 3,
                         "all NULL-key legacy rows coexist (NULLs exempt from unique)")

    # ---- 7. C5 field/type conformance ---------------------------------------

    def test_ac12_conformance_refusals(self):
        self._ratify_shape("v0.1")
        try:
            cases = [
                ({"relation_payload": None}, "relation_payload"),
                ({"relation_payload": json.dumps([1, 2])}, "relation_payload must be a JSON object"),
                ({"business_key": None}, "business_key"),
                ({"business_key": ""}, "business_key"),
                ({"intent_payload": None}, "intent_payload"),
                ({"intent_payload": json.dumps("nope")}, "intent_payload must be a JSON object"),
                ({"intent_payload": json.dumps({"desired_outcome": "ok"})}, "problem_statement"),
                ({"intent_payload": json.dumps({"problem_statement": "p", "desired_outcome": ""})}, "desired_outcome"),
                ({"intent_payload": json.dumps({"problem_statement": "p", "desired_outcome": "d", "priority": "urgent"})}, "priority"),
                ({"intent_payload": json.dumps({"problem_statement": "p", "desired_outcome": "d", "rogue": 1})}, "outside WP1 v0.1 envelope"),
                ({"lineage": json.dumps({"rogue": 1})}, "lineage"),
                ({"decomposition": json.dumps({"steps": "not-an-array"})}, "steps"),
                ({"evidence_obligations": json.dumps({"nope": True})}, "evidence_obligations must be an array"),
                ({"inquiry": json.dumps({"read_set_scope": {}, "evaluator_ref": "e",
                                         "expected_outcome_type": "t",
                                         "evidence_requirements": [],
                                         "fifth": 1})}, "fifth field"),
                ({"inquiry": json.dumps({"read_set_scope": [], "evaluator_ref": "e",
                                         "expected_outcome_type": "t",
                                         "evidence_requirements": []})}, "read_set_scope must be an object"),
            ]
            for i, (overrides, fragment) in enumerate(cases):
                merged = {"wr_id": f"wr-c5-{i}", "business_key": f"bk-c5-{i}"}
                merged.update(overrides)
                self._refused(
                    self._canonical_row(**merged),
                    fragment)
        finally:
            self._unratify_shape("v0.1")

    # ---- 8. single-successor ratification -----------------------------------

    def test_ac13_single_successor_ratification(self):
        self._ratify_shape("v0.1")
        try:
            self._refused(f"""
                INSERT INTO vision.work_request_shape_registry
                    (shape_version, artifact_path, artifact_sha256, ratification_state)
                VALUES ('v0.2', 'x.json', '{"b" * 64}', 'ratified')
            """, "P1030")
        finally:
            self._unratify_shape("v0.1")

    # ---- 9. never-drop guard -------------------------------------------------

    def test_ac14_never_drop_guard(self):
        self._refused("DROP TABLE vision.work_request_shape_registry", "P1022")
        self._refused("DROP TABLE conduit.work_request_events", "P1022")
        # non-pinned tables drop freely
        self._sql("CREATE TABLE vision.tmp_not_pinned (id int)")
        self._sql("DROP TABLE vision.tmp_not_pinned")
        # hatched drop admitted (session-LOCAL: SET + DROP on one connection).
        # A pinned object must NOT be dropped even hatched in this proof —
        # instead prove the hatch releases the guard for a sacrificial pinned-
        # SCHEMA table, then verify pinned objects survived the whole test.
        self._sql("CREATE TABLE vision.tmp_hatched (id int)")
        self._sql_hatched("DROP TABLE vision.tmp_hatched",
                          setting='vision.allow_wr_object_drop')
        # pinned tables still present
        rows = self._sql("""
            SELECT count(*) FROM information_schema.tables
            WHERE table_schema='vision' AND table_name='work_request_shape_registry'
        """)
        self.assertEqual(rows[0][0], 1)


if __name__ == "__main__":
    unittest.main()
