#!/usr/bin/env python3
"""E2E: V191 — bcrypt-at-rest backfill + born-clean CHECKs (real migration,
throwaway DB, issue 59bcd3da remediation).

wr-conf house pattern (V175/V190 companions). The skeleton recreates the
PRE-V191 live shape (census 2026-09-20, titanium): assembly.users with 8
plaintext rows (admin included — the surface user-access-service
validateUser authenticates against) and gateway.users with 2 plaintext
rows (write-orphaned). Then the REAL sql/V191__users_password_bcrypt.sql
applies and the contract is exercised against live constraint behavior —
no mocks on the DB path:

  - backfill: every plaintext password becomes a bcrypt hash ($2…, 60 chars)
  - verification round-trip: pgcrypto crypt(plaintext, hash) == hash proves
    the ORIGINAL credential still works through the standard bcrypt check
    (this is what Java BCryptPasswordEncoder.matches() implements)
  - wrong plaintext fails the round-trip
  - idempotent re-apply: second run is a zero-row no-op (WHERE NOT LIKE '$2%')
  - born-clean CHECKs: a plaintext write is REJECTED by the database itself
    (the seeder class becomes impossible); an empty string is still allowed
    (the '' escape, matching the role CHECKs' convention); a valid bcrypt
    hash is accepted
  - pre-existing hashes are never re-hashed (never-destructive guard)
"""
import os
import sys
import unittest
import uuid

import psycopg2

_REPO_ROOT = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", ".."))
V191_PATH = os.path.join(_REPO_ROOT, "sql", "V191__users_password_bcrypt.sql")

DSN = os.environ.get("CONDUIT_PG_DSN",
                     "postgresql://pguser:pgpass@localhost:5432/postgres")

SKELETON_SQL = """
CREATE SCHEMA assembly;
CREATE SCHEMA gateway;

CREATE TABLE assembly.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    identifier varchar(255) NOT NULL DEFAULT '',
    admin boolean NOT NULL DEFAULT false,
    alias varchar(100) NOT NULL UNIQUE,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    avatar_url varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- gateway.users live shape: bigint PK, no default observed
CREATE TABLE gateway.users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin boolean NOT NULL DEFAULT false,
    alias varchar(255) NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT now(),
    email varchar(255),
    identifier varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now()
);

INSERT INTO assembly.users (alias, email, identifier, password, admin) VALUES
    ('admin',    'admin@localhost',    'admin',  'admin',      true),
    ('copilot',  'copilot@localhost',  'x',      'x',          false),
    ('claude',   'claude@localhost',   'x',      'x',          false),
    ('gemini',   'gemini@localhost',   'x',      'x',          false),
    ('chatgpt',  'chatgpt@localhost',  'x',      'x',          false),
    ('Rover',    'rover@localhost',    'roverpw', 'roverpw',   false),
    ('inspector','inspector@localhost','agent',  'agent',      false),
    ('critic',   'critic@localhost',   'agent',  'agent',      false);

INSERT INTO gateway.users (alias, email, identifier, password) VALUES
    ('admin',    'admin@localhost',    'admin',  'admin'),
    ('testuser', 'test@localhost',     'secret123', 'secret123');
"""


class ThrowawayDB:
    def __init__(self, dbname_prefix):
        self.dbname = f"nexus_v191_{dbname_prefix}_{os.getpid()}_{uuid.uuid4().hex[:6]}"
        self.conn = None

    def __enter__(self):
        admin = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/postgres")
        admin.autocommit = True
        with admin.cursor() as cur:
            cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}"')
            cur.execute(f'CREATE DATABASE "{self.dbname}"')
        admin.close()
        self.conn = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/" + self.dbname)
        self.conn.autocommit = True
        with self.conn.cursor() as cur:
            cur.execute(SKELETON_SQL)
        return self

    def __exit__(self, *exc):
        try:
            if self.conn:
                self.conn.close()
        finally:
            admin = psycopg2.connect(DSN.rsplit("/", 1)[0] + "/postgres")
            admin.autocommit = True
            with admin.cursor() as cur:
                cur.execute(f'DROP DATABASE IF EXISTS "{self.dbname}"')
            admin.close()

    def sql(self, stmt, params=None):
        with self.conn.cursor() as cur:
            cur.execute(stmt, params)
            rows = cur.fetchall() if cur.description else None
        if rows and len(rows) == 1 and len(rows[0]) == 1:
            return rows[0][0]
        return rows

    def expect_error(self, stmt, params=None, fragment=None):
        try:
            self.sql(stmt, params)
        except psycopg2.Error as exc:
            # autocommit: clear the aborted implicit transaction server-side
            self.conn.cursor().execute("ROLLBACK")
            msg = str(exc).split("\n")[0]
            if fragment and fragment not in msg:
                raise AssertionError(
                    f"expected error containing {fragment!r}, got: {msg}")
            return msg
        raise AssertionError("expected the statement to fail")

    def apply_v191(self):
        with open(V191_PATH) as fh:
            self.sql(fh.read())


class BackfillPath(unittest.TestCase):
    def test_01_backfill_and_roundtrip(self):
        db = ThrowawayDB("main")
        with db as d:
            d.apply_v191()
            # Every password on both surfaces is now a bcrypt hash.
            for surf in ("assembly.users", "gateway.users"):
                row = d.sql(
                    f"SELECT count(*) FILTER (WHERE password NOT LIKE '$2%' "
                    f"OR length(password) <> 60) FROM {surf}")
                total = d.sql(f"SELECT count(*) FROM {surf}")
                bad = row if not isinstance(row, tuple) else row[0]
                self.assertEqual(bad, 0, f"{surf}: non-bcrypt rows remain")
                self.assertGreater(total, 0, f"{surf}: skeleton rows missing")
            # Round-trip: the ORIGINAL credentials verify through the exact
            # check Java's BCryptPasswordEncoder.matches() implements.
            # Rows: admin/admin, Rover/roverpw, inspector+critic/agent = 4.
            ok = d.sql(
                "SELECT count(*) FROM assembly.users u "
                "WHERE crypt((CASE u.alias WHEN 'admin' THEN 'admin' "
                "  WHEN 'Rover' THEN 'roverpw' ELSE 'agent' END), u.password) = u.password")
            self.assertEqual(ok, 4)
            self.assertEqual(d.sql(
                "SELECT crypt('admin', password) = password FROM assembly.users "
                "WHERE alias='admin'"), True)
            self.assertEqual(d.sql(
                "SELECT crypt('secret123', password) = password FROM gateway.users "
                "WHERE alias='testuser'"), True)
            # Wrong plaintext fails.
            self.assertEqual(d.sql(
                "SELECT crypt('wrongpass', password) = password FROM assembly.users "
                "WHERE alias='admin'"), False)

    def test_02_idempotent_reapply(self):
        db = ThrowawayDB("reapply")
        with db as d:
            d.apply_v191()
            hashes_before = d.sql(
                "SELECT md5(string_agg(password, '' ORDER BY alias)) FROM assembly.users")
            d.apply_v191()  # second apply must be a no-op
            hashes_after = d.sql(
                "SELECT md5(string_agg(password, '' ORDER BY alias)) FROM assembly.users")
            self.assertEqual(hashes_before, hashes_after,
                             "re-apply re-hashed — WHERE guard broken")

    def test_03_check_rejects_plaintext_and_accepts_hash(self):
        db = ThrowawayDB("check")
        with db as d:
            d.apply_v191()
            # Plaintext write REJECTED by the database itself — the seeder
            # class is now impossible, not merely discouraged.
            d.expect_error(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('sneaky', 'sneaky@localhost', 'pw', 'plaintextpw')",
                fragment="users_password_bcrypt_check")
            d.expect_error(
                "UPDATE assembly.users SET password = 'admin' WHERE alias='admin'",
                fragment="users_password_bcrypt_check")
            # Valid bcrypt hash accepted.
            d.sql(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('hashed', 'hashed@localhost', 'x', "
                "crypt('realpw', gen_salt('bf', 10)))")
            # '' escape hatch still allowed (JPA constructor pattern).
            d.sql(
                "INSERT INTO assembly.users (alias, email, identifier, password) "
                "VALUES ('empty', 'empty@localhost', '', '')")
            # gateway surface equally enforced.
            d.expect_error(
                "INSERT INTO gateway.users (alias, email, identifier, password) "
                "VALUES ('sneaky2', 's2@localhost', 'pw', 'plaintext')",
                fragment="users_password_bcrypt_check")

    def test_04_preexisting_hash_never_rehashed(self):
        db = ThrowawayDB("preserve")
        with db as d:
            # Seed one row already carrying a VALID bcrypt hash for
            # 'originalpw' (computed offline — pgcrypto is not yet installed;
            # the migration brings it). It must survive the backfill untouched.
            d.sql("""
                INSERT INTO assembly.users (alias, email, identifier, password)
                VALUES ('already', 'already@localhost', 'pw',
                        '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjPeGqBQVLfJ9X0nYbRJRBQ8RfV9Aa')
            """)
            pre = d.sql("SELECT password FROM assembly.users WHERE alias='already'")
            d.apply_v191()
            post = d.sql("SELECT password FROM assembly.users WHERE alias='already'")
            self.assertEqual(pre, post, "existing hash was re-hashed")


if __name__ == "__main__":
    unittest.main()
