"""Ports used by the PEB application and governance engine."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Iterator, Protocol
from uuid import UUID

from .domain import (
    ExecutionClaimAdmission,
    PebCapability,
    PebDecision,
    PebState,
    PebTrace,
    PebTransaction,
    PebViolation,
)


class PebStore(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def save_transaction(self, transaction: PebTransaction) -> PebTransaction: ...
    def save_violation(self, violation: PebViolation) -> PebViolation: ...
    def save_state(self, state: PebState) -> PebState: ...
    def save_decision(self, decision: PebDecision) -> PebDecision: ...
    def save_trace(self, trace: PebTrace) -> PebTrace: ...
    def save_capability(self, capability: PebCapability) -> PebCapability: ...
    def list_capabilities(self) -> list[PebCapability]: ...
    def record_kernel_event(self, transaction: PebTransaction) -> PebTransaction | None: ...
    def list_states(self) -> list[PebState]: ...
    def latest_decision(self) -> PebDecision | None: ...
    def health(self) -> dict[str, Any]: ...


class ConduitMcpPort(Protocol):
    def submit_work_request(self, work_request: Any) -> Any: ...
    def get_work_request(self, wr_id: str) -> Any: ...
    def transition_work_request(self, wr_id: str, transition: Any) -> Any: ...
    def issue_receipt(self, receipt: Any) -> Any: ...
    def query_state(self) -> Any: ...


class LosmIrTransitionPort(Protocol):
    def transition(self, wr_id: str, to_state: str, actor: str, reason: str) -> Any: ...
    def get_work_request(self, wr_id: str) -> Any: ...
    def orchestrate(self, wr_id: str) -> Any: ...


class ResolutionExecutionClaimPort(Protocol):
    """Port used by PEB before admitting an execution transaction that carries
    an execution claim.

    The implementation asks the resolution schema to validate the immutable
    evidence linkage and execution context. The worker/model never implements
    this port and cannot self-authorize or self-verify a claim.
    """

    def admit_verified_execution_claim(
        self, peb_transaction_id: UUID, input: Any
    ) -> ExecutionClaimAdmission: ...
