#!/usr/bin/env python3
"""solscript_codegen.py — Regenerate Python contract stubs from the emitted
SOLScript OpenAPI projection.

Chain of custody (regeneration proof, phase P2):

    typespec/v1/solscript/python/{main,models,operations}.tsp   (source of truth)
        → npx tsp compile --emit @typespec/openapi3 (JSON)      (projection)
        → THIS SCRIPT                                            (stub regen)
        → <out>/solscript_contracts.py                           (sandbox)

The generated module is a *projection*, not a second source of truth: the
.tsp is canonical. Field names are emitted snake_case (deterministic
camelCase → snake_case mapping) so the generated stubs can be asserted
field-for-field against the reference dataclasses in
python/SOLScript/solscript/models.py (see run-solscript-regen-proof.py).

Bounded, deterministic, dependency-free (stdlib only).
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
from pathlib import Path

HEADER = '''"""solscript_contracts — GENERATED from typespec/v1/solscript (do not edit).

Regenerated by typespec/v1/scripts/solscript_codegen.py from the OpenAPI
projection of the TypeSpec contract. Canonical source: the .tsp files.
Field names are snake_case aliases of the camelCase wire contract so this
module can be parity-checked against the reference implementation
(python/SOLScript/solscript/models.py).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


JsonValue = Any
'''

UNION_TMPL = '''class {name}(str, Enum):
{members}
'''

DATACLASS_TMPL = '''@dataclass
class {name}:
{fields}
'''


# Deterministic identifier mapping for symbol-valued enum members (the
# SolOperator vocabulary). Values not in this table are sanitized with
# _enum_member_ident(). Keep in sync with models.tsp SolOperator.
SYMBOL_ENUM_MEMBERS = {
    "=": "EQ",
    "<>": "NEQ",
    ">": "GT",
    "<": "LT",
    ">=": "GTE",
    "<=": "LTE",
    "AND": "AND",
    "OR": "OR",
    "NOT": "NOT",
}


def _enum_member_ident(value: str) -> str:
    """Map an enum VALUE to a deterministic Python identifier."""
    if value in SYMBOL_ENUM_MEMBERS:
        return SYMBOL_ENUM_MEMBERS[value]
    ident = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not ident:
        ident = "VALUE"
    if ident[0].isdigit():
        ident = "V_" + ident
    return ident


def camel_to_snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    out = s2.lower()
    if keyword.iskeyword(out):
        out += "_"
    return out


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def py_type(schema: dict, schemas: dict) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "enum" in schema:
        # inline enum: fall back to str
        return "str"
    t = schema.get("type")
    if t == "string":
        fmt = schema.get("format")
        if fmt == "date-time":
            return "datetime"
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"List[{py_type(schema.get('items', {}), schemas)}]"
    if t == "object":
        if "properties" in schema or "additionalProperties" in schema:
            ap = schema.get("additionalProperties")
            if isinstance(ap, dict):
                return f"Dict[str, {py_type(ap, schemas)}]"
            return "Dict[str, Any]"
        return "Dict[str, Any]"
    if t is None and ("anyOf" in schema or "oneOf" in schema):
        variants = schema.get("anyOf") or schema.get("oneOf")
        parts = sorted({py_type(v, schemas) for v in variants})
        return f"Any  # union of: {' | '.join(parts)}"
    return "Any"


def optional(schema: dict, required: bool) -> bool:
    if required:
        return False
    return True


def snake_field(name: str) -> str:
    out = camel_to_snake(name)
    if keyword.iskeyword(out):
        out += "_"
    return out


def generate(openapi_path: Path) -> str:
    doc = json.loads(openapi_path.read_text())
    schemas: dict = doc.get("components", {}).get("schemas", {})
    out_parts = [HEADER]

    # deterministic order: enums first, then models alphabetically
    enum_schemas = {k: v for k, v in schemas.items() if "enum" in v}
    model_schemas = {k: v for k, v in schemas.items() if "enum" not in v and v.get("type") == "object" and "properties" in v}
    skip = {k for k, v in schemas.items() if k not in enum_schemas and k not in model_schemas}

    for name in sorted(enum_schemas):
        sch = enum_schemas[name]
        members = "\n".join(
            f"    {_enum_member_ident(str(v))} = {json.dumps(str(v))}" for v in sch["enum"]
        )
        out_parts.append(UNION_TMPL.format(name=name, members=members))

    for name in sorted(model_schemas):
        sch = model_schemas[name]
        props: dict = sch.get("properties", {})
        required = set(sch.get("required", []))
        lines = []
        for pname in sorted(props):
            pschema = props[pname]
            fname = snake_field(pname)
            ptype = py_type(pschema, schemas)
            if optional(pschema, pname in required):
                ftype = f"Optional[{ptype}]"
                default = "None"
            else:
                ftype = ptype
                if pschema.get("type") == "array":
                    default = "field(default_factory=list)"
                elif "additionalProperties" in pschema or pschema.get("type") == "object":
                    default = "field(default_factory=dict)"
                else:
                    default = '""' if ftype == "str" else "None"
            lines.append(f"    {fname}: {ftype} = {default}")
        if not lines:
            lines = ["    pass"]
        out_parts.append(DATACLASS_TMPL.format(name=name, fields="\n".join(lines)))

    tail = f"\n\n# Not projected from the contract (non-object schemas): {', '.join(sorted(skip)) or 'none'}\n"
    return "\n\n".join(out_parts) + tail


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("openapi", type=Path, help="path to emitted openapi.json")
    ap.add_argument("--out", type=Path, required=True, help="output .py path")
    args = ap.parse_args()
    text = generate(args.openapi)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
