"""Simple event schema validation without external dependencies."""

SCHEMAS = {
    "IdeaCaptured": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea"],
    },
    "WorkflowPlanned": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "idea", "steps"],
    },
    "StepRequested": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step"],
    },
    "StepApproved": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step"],
    },
    "StepRejected": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step"],
    },
    "KernelPanic": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "reason"],
    },
    # Completion event types (generated by handlers)
    "VocabularyDrafted": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
    "RequirementsFormalized": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
    "TypeSpecDrafted": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
    "SpecCompiled": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
    "RefactorDrafted": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
    "Integrated": {
        "required_fields": ["id", "type", "timestamp", "source", "payload"],
        "payload_fields": ["idea_id", "step", "artifact_path"],
    },
}

ALL_KNOWN_TYPES = set(SCHEMAS.keys())


def validate_event(evt):
    """Validate an event dict. Returns (is_valid, error_message)."""
    if not isinstance(evt, dict):
        return False, "Event is not a dictionary"

    evt_type = evt.get("type")
    if not evt_type:
        return False, "Event missing 'type' field"

    if evt_type not in ALL_KNOWN_TYPES:
        return False, f"Unknown event type: '{evt_type}'"

    schema = SCHEMAS[evt_type]

    # Check top-level required fields
    for field in schema["required_fields"]:
        if field not in evt:
            return False, f"Event '{evt_type}' missing required field: '{field}'"

    # Check payload fields
    payload = evt.get("payload", {})
    if not isinstance(payload, dict):
        return False, f"Event '{evt_type}' payload is not a dictionary"

    for field in schema["payload_fields"]:
        if field not in payload:
            return False, f"Event '{evt_type}' payload missing required field: '{field}'"

    return True, None
